### ISSUE TITLE
CuriosityStream error when starting

### ISSUE THREAD

**Issue by Sirove** [matthuisman/slyguy.addons#10]
- Windows 10
- Kodi 19.1
- SlyGuy Common 0.31.1
- SlyGuy Repositary 0.0.2
- CuriosityStream 0.1.4

I followed the instructions on your website and successfully added your repository and installed CuriosityStream but unfortunetely every time I start the addon it just says:
> SlyGuy Common error 
> Check the log for more information.

Log:
```
2021-05-27 11:09:20.342 T:10016    INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-05-27 11:09:32.864 T:4188    ERROR <general>: Control 52 in window 10025 has been asked to focus, but it can't
2021-05-27 11:09:32.890 T:15020    INFO <general>: initializing python engine.
2021-05-27 11:09:33.426 T:15020   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'queue'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\slyguy.curiositystream\default.py", line 3, in <module>
                                                       from resources.lib.plugin import plugin
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\slyguy.curiositystream\resources\lib\plugin.py", line 1, in <module>
                                                       from slyguy import plugin, gui, userdata, signals, inputstream, settings
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\plugin.py", line 14, in <module>
                                                       from . import router, gui, settings, userdata, inputstream, signals, migrate, bookmarks
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\gui.py", line 9, in <module>
                                                       from slyguy.util import set_kodi_string, hash_6
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\util.py", line 17, in <module>
                                                       from six.moves import queue
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\six.py", line 92, in __get__
                                                       result = self._resolve()
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\six.py", line 115, in _resolve
                                                       return _import_module(self.mod)
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\six.py", line 82, in _import_module
                                                       __import__(name)
                                                   ModuleNotFoundError: No module named 'queue'
                                                   -->End of Python script error report<--
                                                   
2021-05-27 11:09:33.445 T:15020    INFO <general>: Python interpreter stopped
2021-05-27 11:09:33.452 T:11324   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://slyguy.curiositystream/
2021-05-27 11:09:33.458 T:4188    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://slyguy.curiositystream/) failed
```

What exactly seems to be the problem? I appreciate your work and would really like to enjoy this addon in particular.

**Comment by matthuisman** [comment]
Looks like maybe slyguy common has corrupt when installing. Maybe try reinstalling it?

**Comment by Sirove** [comment]
Unfortunately the same "SlyGuy Common error" right after "successful" reinstallation.

**Comment by matthuisman** [comment]
queue is missing from your kodi's python install. Maybe try reinstall Kodi?

**Comment by Sirove** [comment]
Yes, that's it! It works, thank you!

**Comment by matthuisman** [comment]
Awesome. Pretty sure the team is aware of it and should be getting it fixed.
