### ISSUE TITLE
Kayo errors

### ISSUE THREAD

**Issue by darksaboteur** [matthuisman/slyguy.addons#11]
Every so often I got a notification saying Kayo addon has encountered an error

```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
 Error Type: <class 'AttributeError'>
 Error Contents: 'datetime.timedelta' object has no attribute 'tzinfo'
 Traceback (most recent call last):
   File "/home/nick/.kodi/addons/plugin.video.kayo.sports/default.py", line 3, in <module>
     from resources.lib.plugin import plugin
   File "/home/nick/.kodi/addons/plugin.video.kayo.sports/resources/lib/plugin.py", line 5, in <module>
     import arrow
   File "/home/nick/.kodi/addons/script.module.slyguy/resources/modules/arrow/__init__.py", line 3, in <module>
     from .api import get, now, utcnow
   File "/home/nick/.kodi/addons/script.module.slyguy/resources/modules/arrow/api.py", line 10, in <module>
     from arrow.factory import ArrowFactory
   File "/home/nick/.kodi/addons/script.module.slyguy/resources/modules/arrow/factory.py", line 19, in <module>
     from arrow.arrow import Arrow
   File "/home/nick/.kodi/addons/script.module.slyguy/resources/modules/arrow/arrow.py", line 1494, in <module>
     Arrow.max = Arrow.fromdatetime(datetime.max)
   File "/home/nick/.kodi/addons/script.module.slyguy/resources/modules/arrow/arrow.py", line 221, in fromdatetime
     if dt.tzinfo is None:
 AttributeError: 'datetime.timedelta' object has no attribute 'tzinfo'
 -->End of Python script error report<--
```

That is from the logs.

I am running Kodi 19.1.0 on Fedora 34 with Python 3.9.5

**Comment by matthuisman** [comment]
could you update slyguy common to 0.32.3 (just pushed)
see if that helps.

**Comment by darksaboteur** [comment]
Thanks for the speedy update! I've updated and will see how it goes. It was an intermittent error so it will take a bit to verify it's fixed.

**Comment by matthuisman** [comment]
its actually a known issue with Python on Kodi 
https://github.com/arrow-py/arrow/issues/738
https://github.com/xbmc/xbmc/issues/17311
https://forum.kodi.tv/showthread.php?tid=350319

But hopefully my work-around sorts it.

**Comment by darksaboteur** [comment]
I'm now seeing a slightly different error
```
2021-06-11 21:47:51.754 T:3657    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'bytes' object has no attribute 'tzinfo'
                                                   Traceback (most recent call last):
                                                     File "/home/nick/.kodi/addons/plugin.video.kayo.sports/default.py", line 3, in <module>
                                                       from resources.lib.plugin import plugin
                                                     File "/home/nick/.kodi/addons/plugin.video.kayo.sports/resources/lib/plugin.py", line 5, in <module>
                                                       import arrow
                                                     File "/home/nick/.kodi/addons/script.module.slyguy/resources/modules/arrow/__init__.py", line 3, in <module>
                                                       from .api import get, now, utcnow
                                                     File "/home/nick/.kodi/addons/script.module.slyguy/resources/modules/arrow/api.py", line 10, in <module>
                                                       from arrow.factory import ArrowFactory
                                                     File "/home/nick/.kodi/addons/script.module.slyguy/resources/modules/arrow/factory.py", line 19, in <module>
                                                       from arrow.arrow import Arrow
                                                     File "/home/nick/.kodi/addons/script.module.slyguy/resources/modules/arrow/arrow.py", line 1495, in <module>
                                                       Arrow.max = Arrow.fromdatetime(dt_datetime.max)
                                                     File "/home/nick/.kodi/addons/script.module.slyguy/resources/modules/arrow/arrow.py", line 223, in fromdatetime
                                                       if dt.tzinfo is None:
                                                   AttributeError: 'bytes' object has no attribute 'tzinfo'
                                                   -->End of Python script error report<--
```

**Comment by matthuisman** [comment]
@darksaboteur

ok, hopefully sorted now with latest Slyguy common 0.32.6
I simply removed those 2x lines from arrow that try to get min and max dates... HAHA
I don't use them anywhere, so no biggy.

Not sure if other issues will pop-up due to that - but think should be ok.

Let me know!

**Comment by darksaboteur** [comment]
Thanks, I've updated and will post if I still see the error

**Comment by matthuisman** [comment]
@darksaboteur
OK to close this issue now?

**Comment by darksaboteur** [comment]
Yep all good now thanks
