### ISSUE TITLE
Paramount + Parse manifest error

### ISSUE THREAD

**Issue by scottydulton** [matthuisman/slyguy.addons#119]
Hey @matthuisman could u take a look at the Paramount + addon, getting this error

2022-01-25 21:28:19.164 T:12404   ERROR <general>: script.module.slyguy - syntax error: line 1, column 0
                                                   Traceback (most recent call last):
                                                     File "C:\Users\stimp\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 209, in do_GET
                                                       self._parse_dash(response)
                                                     File "C:\Users\stimp\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 358, in _parse_dash
                                                       root = parseString(data.encode('utf8'))
                                                     File "C:\Program Files\Kodi\system\python\Lib\xml\dom\minidom.py", line 1969, in parseString
                                                       return expatbuilder.parseString(string)
                                                     File "C:\Program Files\Kodi\system\python\Lib\xml\dom\expatbuilder.py", line 925, in parseString
                                                       return builder.parseString(string)
                                                     File "C:\Program Files\Kodi\system\python\Lib\xml\dom\expatbuilder.py", line 223, in parseString
                                                       parser.Parse(string, True)
                                                   xml.parsers.expat.ExpatError: syntax error: line 1, column 0

**Comment by matthuisman** [comment]
should hopefully be fixed in v0.4.2
re-open if it isn't
