### ISSUE TITLE
Udemy will not login in v0.9.8

### ISSUE THREAD

**Issue by andized** [matthuisman/slyguy.addons#128]
I know this was an issue before in an older version, now my login is failing in v0.9.8 and I am using the correct login credentials (login/password works on the udemy website)

the debug log gives me:

2022-02-16 20:22:46.641 T:1329234816   DEBUG: plugin.video.udemy - Attempt 1/2: POST https://www.udemy.com/api-2.0/auth/udemy-auth/login/3.0/
2022-02-16 20:22:47.175 T:1329234816   DEBUG: plugin.video.udemy - SIGNAL: on_error
2022-02-16 20:22:47.176 T:1329234816   DEBUG: plugin.video.udemy - Mem Cache: Deleted 0 Rows
2022-02-16 20:22:47.176 T:1329234816   DEBUG: plugin.video.udemy - SIGNAL: on_close
2022-02-16 20:22:47.177 T:1329234816   DEBUG: plugin.video.udemy - Failed to login.
                                            Server Message: 
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                yield
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 121, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 62, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.udemy/resources/lib/plugin.py", line 49, in login
                                                api.login(username=username, password=password)
                                              File "/storage/.kodi/addons/plugin.video.udemy/resources/lib/api.py", line 121, in login
                                                raise APIError(_(_.LOGIN_ERROR, msg=data.get('detail', '')))
                                            APIError: Failed to login.
                                            Server Message:

**Comment by matthuisman** [comment]
i just tried and mine logs in fine with 0.9.8

**Comment by andized** [comment]
thank you for the quick reply, the error message is really helpful!
looks like i really just mistyped my login... 🤦‍♂️
