### ISSUE TITLE
Sky Sport Now Playback failed

### ISSUE THREAD

**Issue by makapaka23** [matthuisman/slyguy.addons#176]
OK this time, i'm using the correct NZ ip, however am getting `playback failed - check log` , I'm not sure which log may provide more details as to why this is not working ? The login seems to have worked, just not playback

thanks

**Comment by matthuisman** [comment]
That means the Kodi log. Kodi is giving you that message, not my addon. Go
have a look. You'll probably find they are blocking your vpn.

Does the website work with same vpn?

**Comment by makapaka23** [comment]
thanks for the reply again, ok it seems something wrong with inputstream, no idea, but not your problem :) thanks again (have sent some coffee money for all your greak work)

**Comment by matthuisman** [comment]
Oh, it could be problem.
Send me a link to the log :)

**Comment by makapaka23** [comment]
ah yeh, just reading a bit, looks like u might be right - here is the relevant (i hope) section of the log

`2022-04-11 15:52:23.518 T:8976     INFO <general>: Creating InputStream
2022-04-11 15:52:23.538 T:8976     INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1920 x 1080)
2022-04-11 15:52:23.540 T:8976    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting C:\Program Files\Kodi\addons\inputstream.adaptive\
2022-04-11 15:52:24.258 T:1260    ERROR <general>: script.module.slyguy - mismatched tag: line 8, column 2
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Marka\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 233, in do_GET
                                                       self._parse_dash(response)
                                                     File "C:\Users\Marka\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 395, in _parse_dash
                                                       root = parseString(data.encode('utf8'))
                                                     File "C:\Program Files\Kodi\system\python\Lib\xml\dom\minidom.py", line 1969, in parseString
                                                       return expatbuilder.parseString(string)
                                                     File "C:\Program Files\Kodi\system\python\Lib\xml\dom\expatbuilder.py", line 925, in parseString
                                                       return builder.parseString(string)
                                                     File "C:\Program Files\Kodi\system\python\Lib\xml\dom\expatbuilder.py", line 223, in parseString
                                                       parser.Parse(string, True)
                                                   xml.parsers.expat.ExpatError: mismatched tag: line 8, column 2
2022-04-11 15:52:24.260 T:8976     INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 1, Type: VOD, Download speed: 0.0000 Bytes/s
2022-04-11 15:52:24.261 T:8976     INFO <general>: Creating Demuxer
2022-04-11 15:52:24.263 T:8976     INFO <general>: Opening stream: 1001 source: 256
2022-04-11 15:52:24.790 T:8976    ERROR <general>: AddOnLog: inputstream.adaptive: No MOOV in stream!
2022-04-11 15:52:24.790 T:8976  WARNING <general>: CVideoPlayer::OpenStream - Unsupported stream 1001. Stream disabled.`

**Comment by matthuisman** [comment]
It still seems like they blocking you. Try their website and see if works with same vpn

**Comment by makapaka23** [comment]
ah , right again, I hadn't realised but the video comes up black screen on the website even, tried a couple of different nz servers - would that suggest any vpn won't work ?

**Comment by matthuisman** [comment]
Less known VPNs have a better chance of working
