### ISSUE TITLE
[Disney+] 'Language' object has no attribute 'TRAILER'

### ISSUE THREAD

**Issue by pikkmaster** [matthuisman/slyguy.addons#249]
Hi!

Thanks for this nice addon!
Coreelec version 9.2.8 (s912 box -Minix Neo U9-H), when selecting any category in the Disney+ addon, I get the following error message. Please help.

ERROR: slyguy.disney.plus - 'Language' object has no attribute 'TRAILER'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                yield
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 121, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 62, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/slyguy.disney.plus/resources/lib/plugin.py", line 217, in sets
                                                return _sets(**kwargs)
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 225, in decorated_function
                                                folder, more_results = f(page=real_page, **kwargs)
                                              File "/storage/.kodi/addons/slyguy.disney.plus/resources/lib/plugin.py", line 226, in _sets
                                                items = _process_rows(data.get('items', []), data['type'])
                                              File "/storage/.kodi/addons/slyguy.disney.plus/resources/lib/plugin.py", line 248, in _process_rows
                                                item = _parse_video(row)
                                              File "/storage/.kodi/addons/slyguy.disney.plus/resources/lib/plugin.py", line 364, in _parse_video
                                                item.context.append((_.TRAILER, 'RunPlugin({})'.format(item.info['trailer'])))
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/language.py", line 206, in __getattribute__
                                                attr = object.__getattribute__(self, name)
                                            AttributeError: 'Language' object has no attribute 'TRAILER'

Thanks in advance

**Comment by matthuisman** [comment]
fixed in [v0.12.4](https://github.com/matthuisman/slyguy.addons/commit/51cbb65d08f08099cc437dd1a94a418ca55bf6dd)

**Comment by pikkmaster** [comment]
Thank you very much. It's working. Have a nice day.
