### ISSUE TITLE
Paramount Sports

### ISSUE THREAD

**Issue by scottydulton** [matthuisman/slyguy.addons#264]
Hey @matthuisman trying to watch Australia v New Zealand in paramount sports, recieving this error:

2022-09-22 21:11:19.408 T:18896   ERROR <general>: slyguy.paramount.plus - no element found: line 1, column 0
                                                   Traceback (most recent call last):
                                                     File "C:\Users\stimp\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\signals.py", line 41, in throwable
                                                       yield
                                                     File "C:\Users\stimp\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\router.py", line 121, in dispatch
                                                       function(**params)
                                                     File "C:\Users\stimp\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\plugin.py", line 62, in decorated_function
                                                       item = f(*args, **kwargs)
                                                     File "C:\Users\stimp\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\plugin.py", line 53, in decorated_function
                                                       return f(*args, **kwargs)
                                                     File "C:\Users\stimp\AppData\Roaming\Kodi\addons\slyguy.paramount.plus\resources\lib\plugin.py", line 726, in play
                                                       return _play(video_id)
                                                     File "C:\Users\stimp\AppData\Roaming\Kodi\addons\slyguy.paramount.plus\resources\lib\plugin.py", line 729, in _play
                                                       data = api.play(video_id)
                                                     File "C:\Users\stimp\AppData\Roaming\Kodi\addons\slyguy.paramount.plus\resources\lib\api.py", line 353, in play
                                                       root = parseString(resp.content)
                                                     File "C:\Program Files\Kodi\system\python\Lib\xml\dom\minidom.py", line 1969, in parseString
                                                       return expatbuilder.parseString(string)
                                                     File "C:\Program Files\Kodi\system\python\Lib\xml\dom\expatbuilder.py", line 925, in parseString
                                                       return builder.parseString(string)
                                                     File "C:\Program Files\Kodi\system\python\Lib\xml\dom\expatbuilder.py", line 223, in parseString
                                                       parser.Parse(string, True)
                                                   xml.parsers.expat.ExpatError: no element found: line 1, column 0

**Comment by matthuisman** [comment]
need a full log please

**Comment by scottydulton** [comment]
ill have to wait until next time there's live content

**Comment by matthuisman** [comment]
i also just went to check and the login I was provided by a user no longer has a subscription.
So i won't be able to debug this issue until I can get a new login.
If you can help - get in contact :)
Pretty sure the issue should be pretty simple to fix once I can get on while a live game is playing

**Comment by scottydulton** [comment]
> 

@matthuisman how can i provide you account privately?

**Comment by matthuisman** [comment]
See below :)
https://www.matthuisman.nz/2018/06/looking-for-logins.html

Thank you!

**Comment by scottydulton** [comment]
@matthuisman live content is playing now, however not showing up to even test the stream, Izuzu A-League Men

**Comment by scottydulton** [comment]
ill have to wait until next time there is live content
________________________________

**Comment by matthuisman** [comment]
this was sorted wasn't it?

**Comment by matthuisman** [comment]
please lets just move back to the other ticket:
https://github.com/matthuisman/slyguy.addons/issues/272
