### ISSUE TITLE
TVNZ 1 / 2 / Duke

### ISSUE THREAD

**Issue by ozzymanborn** [matthuisman/slyguy.addons#266]
These 3 channels not work on IPTV NZ & PVR.

Right now all 3 channels works in TVNZ+ app.

(smartdnsproxy used with New Zealand setting)

**Comment by matthuisman** [comment]
All those working 100% for me in NZ.

**Comment by ozzymanborn** [comment]
2022-09-28 01:10:52.663 T:4552     INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.nz.freeview/?_=play&_play=1&slug=mjh-tvnz-1&_is_live=1&_noresume=.pvr
2022-09-28 01:10:52.664 T:16592    INFO <general>: Creating InputStream
2022-09-28 01:10:52.666 T:16592    INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1858 x 1057)
2022-09-28 01:10:53.033 T:11468   ERROR <general>: script.module.slyguy - Invalid m3u8
                                                   Traceback (most recent call last):
                                                     File "C:\0019-PortableKodi\kodi-19.4-Matrix-x64\portable_data\addons\script.module.slyguy\resources\lib\proxy.py", line 232, in do_GET
                                                       self._parse_m3u8(response)
                                                     File "C:\0019-PortableKodi\kodi-19.4-Matrix-x64\portable_data\addons\script.module.slyguy\resources\lib\proxy.py", line 982, in _parse_m3u8
                                                       raise Exception('Invalid m3u8')
                                                   Exception: Invalid m3u8

**Comment by matthuisman** [comment]
tvnz 1: https://d1aacm30l5qvyq.cloudfront.net/master.m3u8
tvnz 2: https://d1zzriaq1vudap.cloudfront.net/master.m3u8
duke: https://d1nd47wrukdtck.cloudfront.net/master.m3u8

Please try the above urls directly and see if it works.
If not, maybe smartdnsproxy needs to add the above domains

**Comment by ozzymanborn** [comment]
Thanks. I will contact with smartdnsproxy support with these domains.

**Comment by matthuisman** [comment]
i assumed the TVNZ website would be using these domains...
I'll check tonight and switch to what they are using

**Comment by matthuisman** [comment]
ok - switched my urls to same as TVNZ - so your streams should now work :)
