### ISSUE TITLE
Kayo Kodi addon failed all of a sudden

### ISSUE THREAD

**Issue by Ignattious** [matthuisman/slyguy.addons#31]
2021-07-22 20:45:14.302 T:140374802061056   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name gui
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.kayo.sports/default.py", line 3, in <module>
                                                from resources.lib.plugin import plugin
                                              File "/storage/.kodi/addons/plugin.video.kayo.sports/resources/lib/plugin.py", line 8, in <module>
                                                from slyguy import plugin, gui, settings, userdata, signals, inputstream
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 14, in <module>
                                                from . import router, gui, settings, userdata, inputstream, signals, migrate, bookmarks
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/gui.py", line 10, in <module>
                                                from slyguy.dns import get_dns_rewrites
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/dns.py", line 7, in <module>
                                                from .mem_cache import cached
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/mem_cache.py", line 11, in <module>
                                                from . import signals, gui, router
                                            ImportError: cannot import name gui
                                            -->End of Python script error report<--

**Comment by matthuisman** [comment]
https://forums.whirlpool.net.au/thread/3p6vxxp3?p=104#r69537588

**Comment by Ignattious** [comment]
Jeez that was quick :)
