### ISSUE TITLE
Disney Plus an Udemy broken with last update

### ISSUE THREAD

**Issue by Rigorini** [matthuisman/slyguy.addons#32]
Both AddOn stop working with the update of July, 22  2021 on Osmc/Raspberry pi 3+

That's error log for both

2021-07-22 13:57:07.014 T:1795158240  NOTICE: ADDON: xbmc.json v10.3.0 installed
2021-07-22 13:57:07.014 T:1795158240  NOTICE: ADDON: xbmc.metadata v2.1.0 installed
2021-07-22 13:57:07.015 T:1795158240  NOTICE: ADDON: xbmc.python v2.26.0 installed
2021-07-22 13:57:07.015 T:1795158240  NOTICE: ADDON: xbmc.webinterface v1.0.0 installed
2021-07-22 13:57:27.262 T:1916588976   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2021-07-22 13:57:29.506 T:1428484320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name gui
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/slyguy.disney.plus/default.py", line 3, in <module>
                                                from resources.lib.plugin import plugin
                                              File "/home/osmc/.kodi/addons/slyguy.disney.plus/resources/lib/plugin.py", line 8, in <module>
                                                from slyguy import plugin, gui, userdata, signals, inputstream, settings
                                              File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 14, in <module>
                                                from . import router, gui, settings, userdata, inputstream, signals, migrate, bookmarks
                                              File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/gui.py", line 10, in <module>
                                                from slyguy.dns import get_dns_rewrites
                                              File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/dns.py", line 7, in <module>
                                                from .mem_cache import cached
                                              File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/mem_cache.py", line 11, in <module>
                                                from . import signals, gui, router
                                            ImportError: cannot import name gui
                                            -->End of Python script error report<--
2021-07-22 13:57:29.722 T:1495261408   ERROR: GetDirectory - Error getting plugin://slyguy.disney.plus/
2021-07-22 13:57:29.723 T:1916588976   ERROR: CGUIMediaWindow::GetDirectory(plugin://slyguy.disney.plus/) failed
2021-07-22 13:57:35.244 T:1916588976   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2021-07-22 13:57:37.349 T:1420091616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name gui
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.udemy/default.py", line 3, in <module>
                                                from resources.lib.plugin import plugin
                                              File "/home/osmc/.kodi/addons/plugin.video.udemy/resources/lib/plugin.py", line 5, in <module>
                                                from slyguy import plugin, gui, settings, userdata, inputstream, signals
                                              File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 14, in <module>
                                                from . import router, gui, settings, userdata, inputstream, signals, migrate, bookmarks
                                              File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/gui.py", line 10, in <module>
                                                from slyguy.dns import get_dns_rewrites
                                              File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/dns.py", line 7, in <module>
                                                from .mem_cache import cached
                                              File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/mem_cache.py", line 11, in <module>
                                                from . import signals, gui, router
                                            ImportError: cannot import name gui
                                            -->End of Python script error report<--
2021-07-22 13:57:37.574 T:1428484320   ERROR: GetDirectory - Error getting plugin://plugin.video.udemy/
2021-07-22 13:57:37.575 T:1916588976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.udemy/) failed
2021-07-22 14:01:02.744 T:1638904032  NOTICE: script.tv.show.next.aired: ### no prior data found
2021-07-22 14:01:04.745 T:1638904032  NOTICE: script.tv.show.next.aired: ### starting data update

**Comment by matthuisman** [comment]
Already fixed with latest common. Update
