### ISSUE TITLE
TVNZ/TVThree/Neon error on load

### ISSUE THREAD

**Issue by Firesphere** [matthuisman/slyguy.addons#34]
When attempting to open either of these three add-ons, I get the following error in the logs:

```
2021-07-23 18:17:40.928 T:2880512880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name gui
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.tvnz.ondemand/default.py", line 3, in <module>
                                                from resources.lib.plugin import plugin
                                              File "/storage/.kodi/addons/plugin.video.tvnz.ondemand/resources/lib/plugin.py", line 6, in <module>
                                                from slyguy import plugin, gui, settings, userdata, inputstream
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 14, in <module>
                                                from . import router, gui, settings, userdata, inputstream, signals, migrate, bookmarks
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/gui.py", line 10, in <module>
                                                from slyguy.dns import get_dns_rewrites
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/dns.py", line 7, in <module>
                                                from .mem_cache import cached
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/mem_cache.py", line 11, in <module>
                                                from . import signals, gui, router
                                            ImportError: cannot import name gui
                                            -->End of Python script error report<--
2021-07-23 18:17:41.061 T:2870989680   ERROR: GetDirectory - Error getting plugin://plugin.video.tvnz.ondemand/
2021-07-23 18:17:41.104 T:3011297888   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tvnz.ondemand/) failed
2021-07-23 18:18:25.441 T:3011297888   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2021-07-23 18:19:57.129 T:2979853168  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
2021-07-23 18:19:59.925 T:3011297888   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2021-07-23 18:20:00.588 T:2880512880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name gui
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/slyguy.neon/default.py", line 3, in <module>
                                                from resources.lib.plugin import plugin
                                              File "/storage/.kodi/addons/slyguy.neon/resources/lib/plugin.py", line 3, in <module>
                                                from slyguy import plugin, gui, userdata, signals, settings
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 14, in <module>
                                                from . import router, gui, settings, userdata, inputstream, signals, migrate, bookmarks
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/gui.py", line 10, in <module>
                                                from slyguy.dns import get_dns_rewrites
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/dns.py", line 7, in <module>
                                                from .mem_cache import cached
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/mem_cache.py", line 11, in <module>
                                                from . import signals, gui, router
                                            ImportError: cannot import name gui
                                            -->End of Python script error report<--
2021-07-23 18:20:00.718 T:2862596976   ERROR: GetDirectory - Error getting plugin://slyguy.neon/
2021-07-23 18:20:00.728 T:3011297888   ERROR: CGUIMediaWindow::GetDirectory(plugin://slyguy.neon/) failed
```

Opening the plugins takes me back to the "Video" section of Kodi.

**Comment by matthuisman** [comment]
Already fixed.
Follow below to force update
https://www.matthuisman.nz/2019/09/how-to-force-kodi-to-update-add-ons.html

**Comment by Firesphere** [comment]
Interesting, do you have any idea how it worked yesterday, but broke today?

Anyways, thanks, and excellent work! "One coffee" coming your way

**Comment by matthuisman** [comment]
I'll do a post about it sometime.
A series of unfortunate events. 
Thanks for the donation 🙂
