### ISSUE TITLE
[Disney+] Server Error: playback.selection-not-found

### ISSUE THREAD

**Issue by Liqianyu** [matthuisman/slyguy.addons#35]
![Screenshots](https://i.loli.net/2021/07/27/pnJuABOskD7GfeQ.png)
Enabling Widevince L1 Secure Device and H.265/1080P for add-on settings will cause errors.
If H.265/1080P is turned off it will play normally.

Logs

> 2021-07-27 11:27:54.575 T:29731   DEBUG <general>: slyguy.disney.plus - API request failed
                                                   Server Error: playback.selection-not-found
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 31, in throwable
                                                       yield
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 113, in dispatch
                                                       function(**params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 65, in decorated_function
                                                       item = f(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 56, in decorated_function
                                                       return f(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.disney.plus/resources/lib/plugin.py", line 523, in play
                                                       playback_data = api.playback_data(playback_url)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.disney.plus/resources/lib/api.py", line 316, in playback_data
                                                       self._check_errors(playback_data)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.disney.plus/resources/lib/api.py", line 141, in _check_errors
                                                       raise APIError(_(error, msg=error_msg))
                                                   resources.lib.api.APIError: API request failed
                                                   Server Error: playback.selection-not-found

**Comment by matthuisman** [comment]
fixed with 0.7.7
