### ISSUE TITLE
[Paramount plus]: This content is not available in your location

### ISSUE THREAD

**Issue by grubitwo** [matthuisman/slyguy.addons#412]
Hello,
I get this error when trying to play something from Paramount Plus.
![screenshot_slyguy_pp_01](https://user-images.githubusercontent.com/127102816/223122828-c3299428-8b94-4038-8dc4-28ce874f088c.png)
[slyguy_paramountplus_debug.log](https://github.com/matthuisman/slyguy.addons/files/10898661/slyguy_paramountplus_debug.log)

Location: Switzerland
This error occurs with Kodi (Matrix) v19.5 LibreELEC 10.0.4 and with Android Kodi (Nexus) v20.0.
With the official Android app the playback works.

**Comment by FKutschera** [comment]
I am having the same Problem.
I am located in Austria and I am using LibreELEC 11.0.0 Kodi Nexus 20.0

**Comment by grubitwo** [comment]
Is there a small hope that this addon will also work in Switzerland?

**Comment by matthuisman** [comment]
is this still an issue?

**Comment by grubitwo** [comment]
Yes the problem still exists.

**Comment by matthuisman** [comment]
thanks. can you please link me to the android playstore page for the android app you use for Paramount+ in Switzerland?

**Comment by grubitwo** [comment]
The link from google playstore is "https://play.google.com/store/apps/details?id=com.cbs.ca".

**Comment by betlit** [comment]
Still seems to be an issue. 
I'm also located in Switzerland.
Tried with OSMC / Kodi 20.2 and Xubuntu 22.04.3 LTS / Kodi 19.4.0

`2023-09-09 16:12:52.885 T:144736   DEBUG <general>: slyguy.paramount.plus - Cache data loaded
2023-09-09 16:12:52.886 T:144736   DEBUG <general>: slyguy.paramount.plus - Router Parsed: 'plugin://slyguy.paramount.plus/?_=play&_play=1&profile_id=40610384&video_id=ut5wpuNl2GpvPwXBxVdr6_GCDyaMT4FY' => play {'_play': '1', 'profile_id': '40610384', 'video_id': 'ut5wpuNl2GpvPwXBxVdr6_GCDyaMT4FY', '_url': 'plugin://slyguy.paramount.plus/?_=play&_play=1&profile_id=40610384&video_id=ut5wpuNl2GpvPwXBxVdr6_GCDyaMT4FY'}
2023-09-09 16:12:52.886 T:144736   DEBUG <general>: slyguy.paramount.plus - Attempt 1/1: GET https://www.intl.paramountplus.com/apps-api/v3.1/androidphone/irdeto-control/session-token.json
2023-09-09 16:12:52.903 T:144789   DEBUG <general>: Thread scriptobs start, auto delete: false
2023-09-09 16:12:53.103 T:144667   DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
2023-09-09 16:12:53.283 T:144736   DEBUG <general>: slyguy.paramount.plus - SSL Cipher: www.intl.paramountplus.com - ('ECDHE-RSA-AES128-GCM-SHA256', 'TLSv1.2', 128)
2023-09-09 16:12:53.416 T:144667   DEBUG <general>: CGLContextEGL::SwapBuffers: sync check blocking
2023-09-09 16:12:53.484 T:144736    INFO <general>: Skipped 3 duplicate messages..
2023-09-09 16:12:53.484 T:144736   DEBUG <general>: slyguy.paramount.plus - Attempt 1/1: GET http://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/ut5wpuNl2GpvPwXBxVdr6_GCDyaMT4FY
2023-09-09 16:12:53.499 T:144667   DEBUG <general>: CGLContextEGL::SwapBuffers: sync check blocking
2023-09-09 16:12:53.551 T:144667    INFO <general>: Skipped 2 duplicate messages..
2023-09-09 16:12:53.551 T:144667   DEBUG <general>: CGLContextEGL::SwapBuffers: sync sleep: 12413
2023-09-09 16:12:53.866 T:144736   DEBUG <general>: slyguy.paramount.plus - SIGNAL: on_error
2023-09-09 16:12:53.866 T:144736   DEBUG <general>: slyguy.paramount.plus - Mem Cache: Deleted 7 Rows
2023-09-09 16:12:53.866 T:144736   DEBUG <general>: slyguy.paramount.plus - SIGNAL: on_close
2023-09-09 16:12:53.867 T:144736   DEBUG <general>: slyguy.paramount.plus - This content is not available in your location.
                                                   Traceback (most recent call last):
                                                     File "/home/shittel/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/home/shittel/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 115, in dispatch
                                                       function(**params)
                                                     File "/home/shittel/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 59, in decorated_function
                                                       item = f(*args, **kwargs)
                                                     File "/home/shittel/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 50, in decorated_function
                                                       return f(*args, **kwargs)
                                                     File "/home/shittel/.kodi/addons/slyguy.paramount.plus/resources/lib/plugin.py", line 679, in play
                                                       return _play(video_id, **kwargs)
                                                     File "/home/shittel/.kodi/addons/slyguy.paramount.plus/resources/lib/plugin.py", line 682, in _play
                                                       data = api.play(video_id)
                                                     File "/home/shittel/.kodi/addons/slyguy.paramount.plus/resources/lib/api.py", line 392, in play
                                                       raise APIError(_(error_msg))
                                                   resources.lib.api.APIError: This content is not available in your location.
`

**Comment by grubitwo** [comment]
Now Paramount also works for me, both on Android and on Libreelec. Thank you

**Comment by matthuisman** [comment]
Strange. I don't think I made any changes... Maybe paramount dis
