### ISSUE TITLE
Kayo Add on won’t work on Kodi 

### ISSUE THREAD

**Issue by Rpg1000** [matthuisman/slyguy.addons#427]
Kayo add on won’t work on kodi 

message says failed to fetch auth token

**Comment by matthuisman** [comment]
Full kodi debug log please. You can Google how to do that

**Comment by musshorn** [comment]
I'm getting the same issue
https://paste.kodi.tv/paqocuvoca.kodi

This appears to be the relevant part
```
2023-03-19 19:01:11.772 T:621     DEBUG <general>: plugin.video.kayo.sports - Attempt 1/2: POST https://auth.streamotion.com.au/oauth/token
2023-03-19 19:01:11.873 T:621     DEBUG <general>: plugin.video.kayo.sports - SIGNAL: on_error
2023-03-19 19:01:11.874 T:621     DEBUG <general>: plugin.video.kayo.sports - Mem Cache: Deleted 0 Rows
2023-03-19 19:01:11.874 T:621     DEBUG <general>: plugin.video.kayo.sports - SIGNAL: on_close
2023-03-19 19:01:11.886 T:621     DEBUG <general>: plugin.video.kayo.sports - Failed to fetch auth token
                                                   Make sure your IP address is allowed (not geo-blocked)
                                                   Try accessing the content via other means (offical app / website) to confirm it's a Kodi add-on issue
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/slyguy.dependencies/resources/modules/requests/models.py", line 910, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 36, in json_override
                                                       return func()
                                                     File "/home/osmc/.kodi/addons/slyguy.dependencies/resources/modules/requests/models.py", line 917, in json
                                                       raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
                                                   requests.exceptions.JSONDecodeError: [Errno Expecting value] <HTML><HEAD>
                                                   <TITLE>Access Denied</TITLE>
                                                   </HEAD><BODY>
                                                   <H1>Access Denied</H1>
                                                    
                                                   You don't have permission to access "http&#58;&#47;&#47;auth&#46;streamotion&#46;com&#46;au&#47;oauth&#47;token" on this server.<P>
                                                   Reference&#32;&#35;18&#46;9bf00117&#46;1679213256&#46;e1c4fdc
                                                   </BODY>
                                                   </HTML>
                                                   : 0
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 121, in dispatch
                                                       function(**params)
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 62, in decorated_function
                                                       item = f(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.kayo.sports/resources/lib/plugin.py", line 54, in login
                                                       if index == -1 or not options[index][1]():
                                                     File "/home/osmc/.kodi/addons/plugin.video.kayo.sports/resources/lib/plugin.py", line 86, in _email_password
                                                       api.login(username=username, password=password)
                                                     File "/home/osmc/.kodi/addons/plugin.video.kayo.sports/resources/lib/api.py", line 119, in login
                                                       self._oauth_token(payload)
                                                     File "/home/osmc/.kodi/addons/plugin.video.kayo.sports/resources/lib/api.py", line 45, in _oauth_token
                                                       token_data = self._session.post(AUTH_URL + '/token', json=data, headers=AUTH_HEADERS, error_msg=_.TOKEN_ERROR).json()
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 316, in <lambda>
                                                       resp.json = lambda func=resp.json, error_msg=error_msg: json_override(func, error_msg)
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 38, in json_override
                                                       raise SessionError(error_msg or _.JSON_ERROR)
                                                   slyguy.exceptions.SessionError: Failed to fetch auth token
                                                   Make sure your IP address is allowed (not geo-blocked)
                                                   Try accessing the content via other means (offical app / website) to confirm it's a Kodi add-on issue
2023-03-19 19:01:11.889 T:526     DEBUG <general>: ------ Window Init (DialogConfirm.xml) ------
```

**Comment by matthuisman** [comment]
script.module.slyguy v0.60.9 installed

Your slyguy common is too old
Please update to latest
