### ISSUE TITLE
ThreeNow error

### ISSUE THREAD

**Issue by Firesphere** [matthuisman/slyguy.addons#469]
2023-06-07 17:13:52.165 T:1362    error <general>: plugin.video.three.now - 'videoRenditions'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 121, in dispatch
                                                       function(**params)
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 62, in decorated_function
                                                       item = f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.three.now/resources/lib/plugin.py", line 184, in show
                                                       folder.add_items(_parse_episodes(row['episodes']))
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.three.now/resources/lib/plugin.py", line 118, in _parse_episodes
                                                       videoid = row['videoRenditions']['videoCloud']['brightcoveId']
                                                                 ~~~^^^^^^^^^^^^^^^^^^^
                                                   KeyError: 'videoRenditions

**Comment by Firesphere** [comment]
I'm getting an error on ThreeNow, when trying to play something on demand.

I've not tried live playback yet.

**Comment by matthuisman** [comment]
You physically in  NZ? No vpn or smart dns?

**Comment by Firesphere** [comment]
Yes, I'm in NZ, so smart DNS or VPN

**Comment by matthuisman** [comment]
Same content on three website works? Can you give example of what content
gives the error?

**Comment by Firesphere** [comment]
Here's the steps:
- Go to Add-ons
- Go to ThreeNow
- Try to play anything

This is specifically on ThreeNow on demand, not on live playback/TV.

**Comment by Firesphere** [comment]
![signal-2023-06-07-175852](https://github.com/matthuisman/slyguy.addons/assets/680570/e63e370d-8175-4691-9a35-a5b25b58517d)

**Comment by matthuisman** [comment]
Might be a new issue then. I'll try take a look

**Comment by Firesphere** [comment]
I just picked a random show on the ThreeNow website, and it seems to work, so it's only on Kodi where things go wrong.

**Comment by Firesphere** [comment]
A bit of support heading your way :)

**Comment by matthuisman** [comment]
cheers for the support! its really appreciated.

Addon should now be fixed with  v0.13.5
Expect the update within the next hour
