### ISSUE TITLE
No module named 'kodi_six' in slyguy.disney.plus

### ISSUE THREAD

**Issue by harmathy** [matthuisman/slyguy.addons#481]
Since a few days the Disney Plus Addon has no content and the following error message appears in the log:

```
2023-06-17 11:02:03.123 T:2054    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'kodi_six'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/slyguy.disney.plus/default.py", line 3, in <module>
                                                       from resources.lib.plugin import plugin
                                                     File "/storage/.kodi/addons/slyguy.disney.plus/resources/lib/plugin.py", line 1, in <module>
                                                       from kodi_six import xbmc
                                                   ModuleNotFoundError: No module named 'kodi_six'
                                                   -->End of Python script error report<--
```

Im on LibreELEC 10.0.4 (Kodi 19.5.0) on a Raspberry Pi 4.

**Comment by harmathy** [comment]
never mind, the add-on wasn't up-to date
