### ISSUE TITLE
slyguy.dependencies JSON decoding errors with Binge

### ISSUE THREAD

**Issue by shtrom** [matthuisman/slyguy.addons#494]
Trying to play either seasons of _And Just Like That on Binge_ doesn't seem to work. I get JSON-decoding errors in the logs, that seem to be thrown from the common addons.

Other shows such as _This is Going to Hurt_ or Paw Patrol (yes, eclectic tastes...) _Pups Save a Snowboard Competition_ work fine.

```
2023-07-10 23:11:55.024 T:12875   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: embedded null character
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/slyguy.dependencies/resources/modules/requests/models.py", line 910, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/site-packages/simplejson/__init__.py", line 525, in loads
                                                     File "/usr/lib/python3.11/site-packages/simplejson/decoder.py", line 372, in decode
                                                     File "/usr/lib/python3.11/site-packages/simplejson/decoder.py", line 402, in raw_decode
                                                     File "/usr/lib/python3.11/site-packages/simplejson/scanner.py", line 79, in scan_once
                                                     File "/usr/lib/python3.11/site-packages/simplejson/scanner.py", line 70, in _scan_once
                                                   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 50, in json_override
                                                       return func()
                                                              ^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.dependencies/resources/modules/requests/models.py", line 917, in json
                                                       raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
                                                   requests.exceptions.JSONDecodeError: [Errno Expecting value]-->End of Python script error report<--
                                                   
2023-07-10 23:11:55.288 T:1264    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://slyguy.binge/?_=play&_play=1&id=130389&play_type=0&start_from=0]
```
In addition, when rebooting, this error was also logged.
```
2023-07-10 23:12:49.970 T:1293    error <general>: script.module.slyguy - Failed to save proxy session
2023-07-10 23:12:49.978 T:1293    error <general>: script.module.slyguy - Object of type bytes is not JSON serializable
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 1490, in stop
                                                       save_session()
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 1450, in save_session
                                                       set_kodi_string('_slyguy_proxy_data', json.dumps(session))
                                                                                             ^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
                                                     File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
                                                     File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
                                                     File "/usr/lib/python3.11/json/encoder.py", line 180, in default
                                                   TypeError: Object of type bytes is not JSON serializable
```

System is Kodi 20.1 on LibreElec / RPi4
Binge 0.4.4 / SlyGuy Common 0.67.8

```
2023-07-10 23:13:41.323 T:1265     info <general>: Starting Kodi (20.1 (20.1.0) Git:20.1-Nexus). Platform: Linux ARM 32-bit
2023-07-10 23:13:41.323 T:1265     info <general>: Using Release Kodi x32
2023-07-10 23:13:41.323 T:1265     info <general>: Kodi compiled 2023-03-18 by GCC 12.2.0 for Linux ARM 32-bit version 6.1.19 (393491)
2023-07-10 23:13:41.323 T:1265     info <general>: Running on BCM2835 with LibreELEC (official): 11.0.1, kernel: Linux ARM 64-bit version 6.1.19
2023-07-10 23:13:41.323 T:1265     info <general>: FFmpeg version/source: 4.4.1-Kodi
```

**Comment by matthuisman** [comment]
ive just tested lots of episodes of "And just like that" and dont have issue.
tested on windows x64 and linux x64

Are you physically in Australia?
Your first error doesnt show where in the binge addon its getting raised..
I'm assuming its when trying to get the JSON from https://play.binge.com.au/api/v1/play

**Comment by shtrom** [comment]
Yep, physically in AU, Internode. It's on a Basic subscription, so the one that now has ads despite paying for it

I turned debug mode on, and yep: https://play.binge.com.au/api/v1/play. There's an `on_error` getting called just after an SSL message.

```
2023-07-11 22:55:43.109 T:26912   debug <general>: CPythonInvoker(93, /storage/.kodi/addons/slyguy.binge/default.py): start processing
2023-07-11 22:55:43.109 T:26912   debug <general>: CPythonInvoker(93): adding args:
2023-07-11 22:55:43.109 T:26912   debug <general>: CPythonInvoker(93):  plugin://slyguy.binge/
2023-07-11 22:55:43.109 T:26912   debug <general>: CPythonInvoker(93):  58
2023-07-11 22:55:43.109 T:26912   debug <general>: CPythonInvoker(93):  ?_=play&_play=1&id=130379&play_type=0&start_from=0
2023-07-11 22:55:43.109 T:26912   debug <general>: CPythonInvoker(93):  resume:false
2023-07-11 22:55:43.109 T:26912   debug <general>: CPythonInvoker(93, /storage/.kodi/addons/slyguy.binge/default.py): entering source directory /storage/.kodi/addons/slyguy.binge
2023-07-11 22:55:43.109 T:26912   debug <general>: CPythonInvoker(93, /storage/.kodi/addons/slyguy.binge/default.py): instantiating addon using automatically obtained id of "slyguy.binge" dependent on version 0.0.0 of the xbmc.python api
2023-07-11 22:55:43.110 T:26912   debug <general>: slyguy.binge - SIGNAL: before_dispatch
2023-07-11 22:55:43.111 T:26912   debug <CAddonSettings[0@slyguy.binge]>: trying to load setting definitions from old format...
2023-07-11 22:55:43.116 T:26912    info <CSettingsManager>: Skipped 1 duplicate messages..
2023-07-11 22:55:43.116 T:26912   debug <CSettingsManager>: requested setting (_addon_md5) was not found.
2023-07-11 22:55:43.116 T:26912   debug <CSettingsManager>: requested setting (_arch) was not found.
2023-07-11 22:55:43.116 T:26912   debug <CSettingsManager>: requested setting (_last_updates_check) was not found.
2023-07-11 22:55:43.116 T:26912   debug <CSettingsManager>: requested setting (_mac) was not found.
2023-07-11 22:55:43.116 T:26912   debug <CSettingsManager>: requested setting (_updates) was not found.
2023-07-11 22:55:43.116 T:26912   debug <CSettingsManager>: requested setting (_wv_last_check) was not found.
2023-07-11 22:55:43.116 T:26912   debug <CSettingsManager>: requested setting (_wv_latest_hash) was not found.
2023-07-11 22:55:43.117 T:26912   debug <general>: slyguy.binge - Cache data loaded
2023-07-11 22:55:43.121 T:26912   debug <general>: slyguy.binge - Rewrites Loaded: 1
2023-07-11 22:55:43.121 T:26912   debug <CSettingsManager>: requested setting (proxy_server) was not found.
2023-07-11 22:55:43.122 T:26912   debug <general>: slyguy.binge - Router Parsed: '?_=play&_play=1&id=130379&play_type=0&start_from=0' => play {'_play': '1', 'id': '130379', 'play_type': '0', 'start_from': '0', '_url': 'plugin://slyguy.binge?_=play&_play=1&id=130379&play_type=0&start_from=0'}
2023-07-11 22:55:43.122 T:26912   debug <general>: slyguy.binge - Attempt 1/1: POST https://play.binge.com.au/api/v1/play
2023-07-11 22:55:43.129 T:26981   debug <general>: Thread ScriptObs start, auto delete: false
2023-07-11 22:55:43.329 T:1265    debug <general>: ------ Window Init (DialogBusy.xml) ------
2023-07-11 22:55:43.382 T:26912   debug <general>: slyguy.binge - SSL Cipher: play.binge.com.au - ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
2023-07-11 22:55:43.679 T:26912   debug <general>: slyguy.binge - SIGNAL: on_error
2023-07-11 22:55:43.679 T:26912   debug <general>: slyguy.binge - Mem Cache: Deleted 0 Rows
2023-07-11 22:55:43.679 T:26912   debug <general>: slyguy.binge - SIGNAL: on_close
2023-07-11 22:55:43.693 T:26912   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: embedded null character
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/slyguy.dependencies/resources/modules/requests/models.py", line 910, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/site-packages/simplejson/__init__.py", line 525, in loads
                                                     File "/usr/lib/python3.11/site-packages/simplejson/decoder.py", line 372, in decode
                                                     File "/usr/lib/python3.11/site-packages/simplejson/decoder.py", line 402, in raw_decode
                                                     File "/usr/lib/python3.11/site-packages/simplejson/scanner.py", line 79, in scan_once
                                                     File "/usr/lib/python3.11/site-packages/simplejson/scanner.py", line 70, in _scan_once
                                                   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 46, in json_override
                                                       return func()
                                                              ^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.dependencies/resources/modules/requests/models.py", line 917, in json
                                                       raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
                                                   requests.exceptions.JSONDecodeError: [Errno Expecting value]-->End of Python script error report<--
                                                   
```


I just checked with a `curl` to make sure it wasn't a certificate / time skew issue, and it doesn't seem to be the case (401, but not a TLS issue).

```
# curl -D - https://play.binge.com.au/api/v1/play
HTTP/2 401 
content-length: 0
www-authenticate: Bearer
x-content-type-options: nosniff
strict-transport-security: max-age=31536000 ; includeSubDomains
x-frame-options: DENY
x-xss-protection: 1 ; mode=block
referrer-policy: no-referrer
expires: Tue, 11 Jul 2023 13:02:54 GMT
cache-control: max-age=0, no-cache, no-store
pragma: no-cache
date: Tue, 11 Jul 2023 13:02:54 GMT
access-control-allow-origin: *
```

And it works with other programs:

```
2023-07-11 23:01:41.911 T:27003   debug <general>: slyguy.binge - Attempt 1/1: POST https://play.binge.com.au/api/v1/play
2023-07-11 23:01:41.925 T:28305   debug <general>: Thread ScriptObs start, auto delete: false
2023-07-11 23:01:42.125 T:1265    debug <general>: ------ Window Init (DialogBusy.xml) ------
2023-07-11 23:01:42.164 T:27003   debug <general>: slyguy.binge - SSL Cipher: play.binge.com.au - ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
2023-07-11 23:01:42.449 T:27003   debug <general>: slyguy.binge - Attempt 1/1: GET https://cdnselectionserviceapi.binge.com.au/web/usecdn/unknown/VOD
2023-07-11 23:01:42.676 T:27003   debug <general>: slyguy.binge - SSL Cipher: cdnselectionserviceapi.binge.com.au - ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
2023-07-11 23:01:42.824 T:27003   debug <general>: slyguy.binge - Stream CDN: CLOUDFRONT | Stream Format: drm-dash-hevc
2023-07-11 23:01:42.825 T:27003 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
```

**Comment by shtrom** [comment]
Ah! I added a `log(resp)` in the HTTP request attempt loop in slyguy.common, and got this:

```
2023-07-11 23:18:00.952 T:30078   debug <general>: slyguy.binge - <Response [403]>
```

For programs that work, I get a 200 instead.

**Comment by matthuisman** [comment]
hmm. 403 = forbidden.

I tried with the same kwargs / payload as your 403 and it worked.

I wonder if its something to do with the sub tier.
ive only got access to Standard tier.
Suspect the BASIC may send another attribute / different process

**Comment by matthuisman** [comment]
oh yup. looks like there is a v3 api playback url that takes a different payload. ill try implement that

**Comment by shtrom** [comment]
Thanks mate!

(I mean, it's potentially a blessing in disguise, I get to do something else rather than watching _And Just Like That).

**Comment by shtrom** [comment]
Ok, so I just tried v0.4.7 (and common 0.68.2).

It doesn't error uncontrollably, but I now get a message that says “Failed to get asset. Server Message: Insufficient quality entitlements”

I tried to fiddle with the config, to no avail:
1. disable HEVC
2. playback quality to
  * lowest
  * disabled
  * bypass
  * best
  * ask
and combinations thereof, but all with the same outcome.

I still get a stack trace in the logs:

```
2023-07-12 22:16:31.864 T:17430   debug <general>: slyguy.binge - Cache data loaded
2023-07-12 22:16:31.865 T:17430   debug <general>: slyguy.binge - Rewrites Loaded: 1
2023-07-12 22:16:31.866 T:17430   debug <general>: slyguy.binge - Router Parsed: '?_=play&_play=1&id=130379&play_type=0&start_from=0' => play {'_play': '1', 'id': '130379', 'play_type': '0', 'start_from': '0', '_url': 'plugin://slyguy.binge?_=play&_play=1&id=130379&play_type=0&start_from=0'}
2023-07-12 22:16:31.866 T:17430   debug <general>: slyguy.binge - Attempt 1/1: GET https://api.binge.com.au/v1/private/assets/130379
2023-07-12 22:16:32.090 T:17430   debug <general>: slyguy.binge - SSL Cipher: api.binge.com.au - ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
2023-07-12 22:16:32.361 T:17430   debug <general>: slyguy.binge - Attempt 1/1: POST https://play.binge.com.au/api/v3/play
2023-07-12 22:16:32.654 T:17430   debug <general>: slyguy.binge - SSL Cipher: play.binge.com.au - ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
2023-07-12 22:16:32.937 T:17430   debug <general>: slyguy.binge - SIGNAL: on_error
2023-07-12 22:16:32.937 T:17430   debug <general>: slyguy.binge - Mem Cache: Deleted 0 Rows
2023-07-12 22:16:32.937 T:17430   debug <general>: slyguy.binge - SIGNAL: on_close
2023-07-12 22:16:32.942 T:17430   debug <general>: slyguy.binge - Failed to get asset.
                                                   Server Message: Unsufficient quality entitlements
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 121, in dispatch
                                                       function(**params)
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 62, in decorated_functio
n
                                                       item = f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 53, in decorated_functio
n
                                                       return f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.binge/resources/lib/plugin.py", line 559, in play
                                                       playback = api.stream(id)
                                                                  ^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.binge/resources/lib/api.py", line 192, in stream
                                                       raise APIError(_(_.ASSET_ERROR, msg=msg))
                                                   resources.lib.api.APIError: Failed to get asset.
                                                   Server Message: Unsufficient quality entitlements
2023-07-12 22:16:34.147 T:17430   debug <general>: slyguy.binge - Rewrites Loaded: 1
2023-07-12 22:16:34.149 T:17430   debug <general>: slyguy.binge - SIGNAL: after_dispatch
2023-07-12 22:16:34.154 T:17430   debug <general>: slyguy.binge - SIGNAL: on_close
2023-07-12 22:16:34.155 T:17430   debug <general>: CPythonInvoker(210, /storage/.kodi/addons/slyguy.binge/default.py): script successfully run
2023-07-12 22:16:34.193 T:1265     info <general>: VideoPlayer::OpenFile: plugin://slyguy.binge/?_=play&_play=1&id=130379&play_type=0&start_from=0
2023-07-12 22:16:34.197 T:17487   debug <general>: script.module.slyguy - REQUEST IN: stop.m3u8 (GET)
2023-07-12 22:16:34.200 T:17456   debug <general>: Loading settings for plugin://slyguy.binge/?_=play&_play=1&id=130379&play_type=0&start_from=0
2023-07-12 22:16:34.201 T:17487   debug <general>: script.module.slyguy - Session created from proxy data
2023-07-12 22:16:34.228 T:1265    debug <general>: CVideoGUIInfo::InitCurrentItem(plugin://slyguy.binge/?_=play&_play=1&id=130379&play_type=0&start_from=0)
2023-07-12 22:16:34.228 T:1265    debug <general>: CPlayerGUIInfo::InitCurrentItem(plugin://slyguy.binge/?_=play&_play=1&id=130379&play_type=0&start_from=0)
2023-07-12 22:16:34.702 T:17487   debug <general>: script.module.slyguy - RESPONSE OUT: stop.m3u8 (200)
```

Ok, printing the `kwargs` again, I see
```
 {'data': None, 'json': {'assetId': '130379', 'application': {'name': 'binge', 'appId': 'binge.com.au'}
, 'device': {'id': 'bc1e95db-723d-48fc-8012-effa322bdbc8', 'type': 'android'}, 'player': {'name': 'exoPlayerTV'}, 'ads': {'optOut': True}, 'capabilities': {'codecs': ['
avc', 'hevc']}, 'session': {'intent': 'playback'}}, 'headers': {'authorization': 'Bearer eyJ...wA'}}
```
and I suspect it's choking on the `'ads': {'optOut': True}` with a basic plan...

Nope. Same things with `'ads': {'optOut': True}`, or commenting the `ads` altogether in the request in `slyguy.binge`'s `api.py`/`stream()`.

**Comment by matthuisman** [comment]
I suspect there must be another argument requesting lower quality. Use
chrome web tools and look at the request their website makes to the play
endpoint

**Comment by matthuisman** [comment]
Alternatively, you could create a new trial Basic account for me to use (i dont have aussie mobile so cant sign up) or you could change your password to something temporally to give me access. I would be able to find the issue pretty quick i suspect once I have the correct type of login

**Comment by shtrom** [comment]
Here's the browser request to https://play.binge.com.au/api/v3/play

```
{
        "ads": {"optOut": false},
        "application": {"appId": "binge.com.au", "name": "binge", "version": "9.1.0"},
        "assetId": "130382",
        "browser": {
                "version": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
        },
        "capabilities": {"codecs": ["avc"]},
        "device": {"id": "433b867e-a795-42cd-bb3f-fbf0ca83069c", "type": "desktop"},
        "os": {
                "name": "Browser",
                "version": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
        },
        "player": {"name": "VideoFS", "version": "10.1.1"},
        "session": {"intent": "playback"}
}
```

**Comment by shtrom** [comment]
`kwargs` with HEVC disabled in settings look as expected: no `hevc` in the capabilities.
```
{'data': None, 'json': {'assetId': '130379', 'application': {'name': 'binge', 'appId': 'binge.com.au'}, 'device': {'id': 'bc1e95db-723d-48fc-8012-effa322bdbc8', 'type': 'android'}, 'player': {'name': 'exoPlayerTV'}, 'capabilities': {'codecs': ['avc']}, 'session': {'intent': 'playback'}}, 'headers': {'authorization': 'Bearer eyJ...yLg'}}
```

**Comment by shtrom** [comment]
Same thing with literally the same params from the browser...

```
2023-07-14 23:13:32.063 T:18010   debug <general>: slyguy.binge - SSL Cipher: api.binge.com.au - ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
2023-07-14 23:13:32.272 T:18010   debug <general>: slyguy.binge - Attempt 1/1: POST https://play.binge.com.au/api/v3/play
2023-07-14 23:13:32.272 T:18010   debug <general>: slyguy.binge - {'data': None, 'json': {'ads': {'optOut': False}, 'application': {'appId': 'binge.com.au', 'name': 'binge', 'version': '9.1.0'}, 'assetId': '130382', 'browser': {'version': 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0'}, 'capabilities': {'codecs': ['avc']}, 'device': {'id': '<same-uuid-as-before>', 'type': 'desktop'}, 'os': {'name': 'Browser', 'version': 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0'}, 'player': {'name': 'VideoFS', 'version': '10.1.1'}, 'session': {'intent': 'playback'}}, 'headers': {'authorization': 'Bearer eyJ...Lg'}}
2023-07-14 23:13:32.489 T:18010   debug <general>: slyguy.binge - SSL Cipher: play.binge.com.au - ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
2023-07-14 23:13:32.666 T:18010   debug <general>: slyguy.binge - SIGNAL: on_error
2023-07-14 23:13:32.666 T:18010   debug <general>: slyguy.binge - Mem Cache: Deleted 0 Rows
2023-07-14 23:13:32.666 T:18010   debug <general>: slyguy.binge - SIGNAL: on_close
2023-07-14 23:13:32.669 T:18010   debug <general>: slyguy.binge - Failed to get asset.
                                                   Server Message: Unsufficient quality entitlements
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 121, in dispatch
                                                       function(**params)
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 62, in decorated_function
                                                       item = f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 53, in decorated_function
                                                       return f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.binge/resources/lib/plugin.py", line 559, in play
                                                       playback = api.stream(id)
                                                                  ^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.binge/resources/lib/api.py", line 209, in stream
                                                       raise APIError(_(_.ASSET_ERROR, msg=msg))
                                                   resources.lib.api.APIError: Failed to get asset.
                                                   Server Message: Unsufficient quality entitlements
```

**Comment by shtrom** [comment]
Alright... Sending you some account details.

**Comment by shtrom** [comment]
Same thing with literally the same params from the browser...

```
2023-07-14 23:13:32.063 T:18010   debug <general>: slyguy.binge - SSL Cipher: api.binge.com.au - ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
2023-07-14 23:13:32.272 T:18010   debug <general>: slyguy.binge - Attempt 1/1: POST https://play.binge.com.au/api/v3/play
2023-07-14 23:13:32.272 T:18010   debug <general>: slyguy.binge - {'data': None, 'json': {'ads': {'optOut': False}, 'application': {'appId': 'binge.com.au', 'name': 'binge', 'version': '9.1.0'}, 'assetId': '130382', 'browser': {'version': 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0'}, 'capabilities': {'codecs': ['avc']}, 'device': {'id': '<same-uuid-as-before>', 'type': 'desktop'}, 'os': {'name': 'Browser', 'version': 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0'}, 'player': {'name': 'VideoFS', 'version': '10.1.1'}, 'session': {'intent': 'playback'}}, 'headers': {'authorization': 'Bearer eyJ...Lg'}}
2023-07-14 23:13:32.489 T:18010   debug <general>: slyguy.binge - SSL Cipher: play.binge.com.au - ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
2023-07-14 23:13:32.666 T:18010   debug <general>: slyguy.binge - SIGNAL: on_error
2023-07-14 23:13:32.666 T:18010   debug <general>: slyguy.binge - Mem Cache: Deleted 0 Rows
2023-07-14 23:13:32.666 T:18010   debug <general>: slyguy.binge - SIGNAL: on_close
2023-07-14 23:13:32.669 T:18010   debug <general>: slyguy.binge - Failed to get asset.
                                                   Server Message: Unsufficient quality entitlements
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 121, in dispatch
                                                       function(**params)
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 62, in decorated_function
                                                       item = f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 53, in decorated_function
                                                       return f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.binge/resources/lib/plugin.py", line 559, in play
                                                       playback = api.stream(id)
                                                                  ^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.binge/resources/lib/api.py", line 209, in stream
                                                       raise APIError(_(_.ASSET_ERROR, msg=msg))
                                                   resources.lib.api.APIError: Failed to get asset.
                                                   Server Message: Unsufficient quality entitlements
```

**Comment by matthuisman** [comment]
thanks for your help.
[v0.4.8](https://github.com/matthuisman/slyguy.addons/commit/7e0da337aa8c7e771212ef0d3217294673f3f0b7) just pushed that adds support for basic package :) enjoy!
