### ISSUE TITLE
Rating tag attribute in _ListItemInfoTag doesnt always return a valid number

### ISSUE THREAD

**Issue by Spartan51150** [matthuisman/slyguy.addons#523]
When using the binge addon I noted some movies such as "The Invitation" actually return a "-" string instead of a float for this and as such the addon fails to load the list of items as it cannot convert the string into a float.

```
2023-08-05 21:44:37.829 T:55024   error <general>: slyguy.binge - could not convert string to float: '-'
      Traceback (most recent call last):
        File "/home/kodi/.kodi/addons/slyguy.dependencies/resources/modules/infotagger/listitem.py", line 69, in set_info
          func(v)
      TypeError: must be real number, not str
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/kodi/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
          yield
        File "/home/kodi/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 115, in dispatch
          function(**params)
        File "/home/kodi/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 69, in decorated_function
          item.display()
        File "/home/kodi/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 702, in display
          li = item.get_li()
        File "/home/kodi/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 594, in get_li
          return super(Item, self).get_li(*args, **kwargs)
        File "/home/kodi/.kodi/addons/script.module.slyguy/resources/modules/slyguy/gui.py", line 306, in get_li
          ListItemInfoTag(li, 'video').set_info(info)
        File "/home/kodi/.kodi/addons/slyguy.dependencies/resources/modules/infotagger/listitem.py", line 87, in set_info
          func(_tag_attr['convert'](v))  # Attempt to force conversion to correct type
      ValueError: could not convert string to float: '-'
```

I resolved issue locally by changing:

```
except TypeError:
                func(_tag_attr['convert'](v))  # Attempt to force conversion to correct type
```

to

```
except TypeError:
    if v == '-' and k == 'rating': # Is a rating key with value of '-'
        continue
    func(_tag_attr['convert'](v))  # Attempt to force conversion to correct type
```

**Comment by matthuisman** [comment]
Fixed with latest slyguy common
