### ISSUE TITLE
osmc (Rpi4): disneyplus add-on stops with error since today

### ISSUE THREAD

**Issue by heidricha** [matthuisman/slyguy.addons#528]
the Disney plus addon stopped working, just drops this message from today:

```
2023-08-06 16:09:49.897 T:13952   error <general>: GetDirectory - Error getting plugin://slyguy.disney.plus/?_=watchlist
2023-08-06 16:09:49.921 T:27552   error <general>: CGUIMediaWindow::GetDirectory(plugin://slyguy.disney.plus/?_=watchlist) failed
2023-08-06 16:09:52.536 T:13977    info <CUPnPServer[osmc]>: Received Browse DirectChildren request for object 'musicdb://songs/', with sort criteria
2023-08-06 16:10:02.290 T:27552    info <general>: Skipped 3 duplicate messages..
2023-08-06 16:10:02.290 T:27552    info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2023-08-06 16:10:02.477 T:10008   error <general>: GetDirectory - Error getting -
2023-08-06 16:10:03.475 T:13953   error <general>: slyguy.disney.plus - 'xbmc.InfoTagVideo' object has no attribute 'setDateTime'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 115, in dispatch
                                                       function(**params)
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 69, in decorated_function
                                                       item.display()
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 702, in display
                                                       li = item.get_li()
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 594, in get_li
                                                       return super(Item, self).get_li(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/gui.py", line 310, in get_li
                                                       ListItemInfoTag(li, 'video').set_info(info)
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/listitem.py", line 67, in set_info
                                                       func = getattr(self._info_tag, _tag_attr['attr'])
                                                   AttributeError: 'xbmc.InfoTagVideo' object has no attribute 'setDateTime'
```

**Comment by mh4ckt3mh4ckt1c4s** [comment]
I confirm, same problem since today, using latest plugin version (0.14.1).

**Comment by ebuckland81** [comment]
Confirmed on my Rock 4 SE running LibreElec 11.0.1 too. Disney+ add-on version is 0.14.1. I have tried logging out and in again as well as re-starting the system.

**Comment by matthuisman** [comment]
[script.module.slyguy -> v0.70.4](https://github.com/matthuisman/slyguy.addons/commit/114012167a1b30844c2bdb6bd002d790f9dda5d9) fixed that
