### ISSUE TITLE
Bein Connect MENA login issue

### ISSUE THREAD

**Issue by markeymark** [matthuisman/slyguy.addons#539]
Tried to login tonight and getting an error

```
2023-08-17 19:51:19.619 T:12940    INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddon: slyguy.bein.connect v0.2.9 installed
2023-08-17 19:51:23.160 T:8020     INFO <general>: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
2023-08-17 19:51:35.444 T:8020     INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2023-08-17 19:51:35.522 T:21916    INFO <general>: initializing python engine.
2023-08-17 19:51:35.790 T:21916    INFO <general>: CPythonInvoker(6, C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.bein.connect\default.py): script successfully run
2023-08-17 19:51:37.067 T:21916    INFO <general>: initializing python engine.
2023-08-17 19:51:37.158 T:8020     INFO <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
2023-08-17 19:51:39.443 T:8020     INFO <general>: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY
2023-08-17 19:52:01.147 T:21916   ERROR <general>: slyguy.bein.connect - ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
                                                   Traceback (most recent call last):
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\connectionpool.py", line 704, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\connectionpool.py", line 386, in _make_request
                                                       self._validate_conn(conn)
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\connectionpool.py", line 1041, in _validate_conn
                                                       conn.connect()
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\connection.py", line 416, in connect
                                                       self.sock = ssl_wrap_socket(
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\session.py", line 272, in _ssl_wrap_socket_impl
                                                       ssl_obj = orig_ssl_wrap_socket_impl(*args, **kwargs)
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\util\ssl_.py", line 494, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 500, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1040, in _create
                                                       self.do_handshake()
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1309, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\requests\adapters.py", line 440, in send
                                                       resp = conn.urlopen(
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\connectionpool.py", line 786, in urlopen
                                                       retries = retries.increment(
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\util\retry.py", line 550, in increment
                                                       raise six.reraise(type(error), error, _stacktrace)
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\packages\six.py", line 769, in reraise
                                                       raise value.with_traceback(tb)
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\connectionpool.py", line 704, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\connectionpool.py", line 386, in _make_request
                                                       self._validate_conn(conn)
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\connectionpool.py", line 1041, in _validate_conn
                                                       conn.connect()
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\connection.py", line 416, in connect
                                                       self.sock = ssl_wrap_socket(
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\session.py", line 272, in _ssl_wrap_socket_impl
                                                       ssl_obj = orig_ssl_wrap_socket_impl(*args, **kwargs)
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\urllib3\util\ssl_.py", line 494, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 500, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1040, in _create
                                                       self.do_handshake()
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1309, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\session.py", line 313, in request
                                                       result = super(RawSession, self).request(method, session_data['url'], **kwargs)
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\requests\sessions.py", line 529, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\requests\sessions.py", line 645, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.dependencies\resources\modules\requests\adapters.py", line 501, in send
                                                       raise ConnectionError(err, request=request)
                                                   requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2023-08-17 19:52:02.675 T:8020     INFO <general>: Skipped 1 duplicate messages..
2023-08-17 19:52:02.675 T:8020     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2023-08-17 19:52:05.408 T:18308   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://slyguy.bein.connect/?_=login
2023-08-17 19:52:05.409 T:21916    INFO <general>: CPythonInvoker(6, C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.bein.connect\default.py): script successfully run
2023-08-17 19:52:05.441 T:8020    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://slyguy.bein.connect/?_=login) failed
2023-08-17 19:52:05.454 T:21916    INFO <general>: initializing python engine.
2023-08-17 19:52:05.456 T:21916    INFO <general>: CPythonInvoker(6, C:\Users\mcunn\AppData\Roaming\Kodi\addons\slyguy.bein.connect\default.py): script successfully run
```

**Comment by matthuisman** [comment]
Are you physically in a supported men's country? Does their website or app
still work?
