### ISSUE TITLE
[GPIO Monitor] AttributeError: module 'collections' has no attribute 'Mapping' on newer Python versions

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#545]
```
error <general>: GetDirectory - Error getting plugin://plugin.program.gpio.monitor/
2023-08-29 15:21:54.749 T:681 error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.gpio.monitor/) failed
2023-08-29 15:22:05.036 T:681 info <general>: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
2023-08-29 15:22:08.393 T:1386 error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'AttributeError'>
Error Contents: module 'collections' has no attribute 'Mapping'
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.program.gpio.monitor/default.py", line 3, in <module>
from resources.lib.plugin import plugin
File "/storage/.kodi/addons/plugin.program.gpio.monitor/resources/lib/plugin.py", line 7, in <module>
from . import gpio
File "/storage/.kodi/addons/plugin.program.gpio.monitor/resources/lib/gpio.py", line 47, in <module>
import gpiozero
File "/storage/.kodi/addons/plugin.program.gpio.monitor/resources/lib/gpiozero/__init__.py", line 22, in <module>
from .devices import (
File "/storage/.kodi/addons/plugin.program.gpio.monitor/resources/lib/gpiozero/devices.py", line 38, in <module>
from .compat import frozendict
File "/storage/.kodi/addons/plugin.program.gpio.monitor/resources/lib/gpiozero/compat.py", line 60, in <module>
class frozendict(collections.Mapping):
^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Mapping'
-->End of Python script error report<--
```

**Comment by matthuisman** [comment]
`collections.Mapping has been deprecated since Python 3.3 and was removed from the collections module In Python 3.10. In Python 3.3 - 3.9 `

**Comment by matthuisman** [comment]
this issue now fixed with [plugin.program.gpio.monitor -> v0.1.8](https://github.com/matthuisman/slyguy.addons/commit/5413ca1dee513215ae894c6530089c057bd10dd1)
