### ISSUE TITLE
[NEON] Playback error "Brightcove: Designated resource not found" 

### ISSUE THREAD

**Issue by Firesphere** [matthuisman/slyguy.addons#550]
On NEON, we tried to play the show "The Good Doctor".
Specifically, Season 5.
This season did play before, but today gave the error (summarised):
```
2023-09-10 21:25:50.329 T:26677   debug <general>: slyguy.neon - Could not find a media source from Brightcove
                                                   Server Message: The designated resource was not found.
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 115, in dispatch
                                                       function(**params)
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 59, in decorated_function
                                                       item = f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 50, in decorated_function
                                                       return f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.neon/resources/lib/plugin.py", line 250, in play
                                                       item = api.get_brightcove_src(referenceID, jwt_token)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.neon/resources/lib/api.py", line 145, in get_brightcove_src
                                                       return util.process_brightcove(data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/util.py", line 368, in process_brightcove
                                                       raise Error(_(_.NO_BRIGHTCOVE_SRC, error=msg))
                                                   slyguy.exceptions.Error: Could not find a media source from Brightcove
                                                   Server Message: The designated resource was not found.
```

Episode 1 nor episode 18 from season 5 would not play.

I have a full debug log, but it's a bit large. See attached.
[kodi.zip](https://github.com/matthuisman/slyguy.addons/files/12567935/kodi.zip)

**Comment by matthuisman** [comment]
your log cuts off the start - which is most important and tells me the versions of all the addons

**Comment by matthuisman** [comment]
im trying to test now but the login i have access it is "basic" plan and can only stream one at a time and the user is using it currently.

If you can provide a login that will work for me to test with, get in touch:
https://www.matthuisman.nz/2018/06/looking-for-logins.html

**Comment by Firesphere** [comment]
> your log cuts off the start - which is most important and tells me the versions of all the addons

Hmmm, I'll see if I can get that via a reboot. I cut off the top of the log, because it was all repeating "getting weather update", as the Kodi box had been sitting doing nothing but that all day.

Will probably be tomorrow though.

p.s.
Sadly, I also only have a basic plan myself, so can't really that easily share either :(

**Comment by matthuisman** [comment]
thats ok. ill keep trying the login i have. im sure they should stop streaming eventually so i can see the requests i need :)
