### ISSUE TITLE
Stan - Unexpected Error

### ISSUE THREAD

**Issue by truman11** [matthuisman/slyguy.addons#558]
Opening any sub-category on Stan brings an Unexpected Error
RPi4 Kodi 20.2, Stan (0.4.2/0.71.9)

```
2023-09-22 00:30:54.674 T:20988   error <general>: plugin.video.stan.au - 'description'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 115, in dispatch
                                                       function(**params)
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 59, in decorated_function
                                                       item = f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 208, in decorated_function
                                                       folder, more_results = f(**kwargs)
                                                                              ^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.stan.au/resources/lib/plugin.py", line 229, in parse
                                                       items = _process_entries(data['entries'])
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.stan.au/resources/lib/plugin.py", line 328, in _process_entries
                                                       item.info['plot'] = u'[B]{}[/B]\n\n{}'.format(start_date.to('local').format('MMM Do h:mm A'), row['description'])
                                                                                                                                                     ~~~^^^^^^^^^^^^^^^
                                                   KeyError: 'description'

```

**Comment by matthuisman** [comment]
should now be fixed with [v0.4.3](https://github.com/matthuisman/slyguy.addons/commit/779f085e7cf665203e7a812ec3e1fef17217bc81)

looks like they removed a bunch of information from the main json call and now just return it in individual calls lazily.
Which doesnt work really with Kodi :(

**Comment by moey44** [comment]
![Uploading image.jpg…]()

**Comment by austreams** [comment]
same issue with stan 0.4.3/0.71.9

**Comment by grapenose** [comment]
Still an issue with 0.4.3

**Comment by matthuisman** [comment]
what is the error now?

**Comment by matthuisman** [comment]
try with 0.4.4

**Comment by austreams** [comment]
thanks @matthuisman you’re a legend mate
