### ISSUE TITLE
foxtel go issue

### ISSUE THREAD

**Issue by liam8888999** [matthuisman/slyguy.addons#571]
hi. when trying to access a channel i am getting a plugin error, however if i try it a couple of times it then works.

```python
2023-09-26 11:59:00.828 T:3738883   error <general>: plugin.video.foxtel.go - Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 115, in dispatch
                                                       function(**params)
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 59, in decorated_function
                                                       item = f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 50, in decorated_function
                                                       return f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/plugin.py", line 432, in play
                                                       return _play(media_type, id)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/plugin.py", line 435, in _play
                                                       url, license_url = api.play(media_type, id)
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/api.py", line 309, in play
                                                       self._refresh_token()
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/api.py", line 42, in _refresh_token
                                                       data = self._session.post('/auth.class.api.php/logon/{site_id}'.format(site_id=VOD_SITEID), data=payload)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/slyguy.dependencies/resources/modules/requests/sessions.py", line 577, in post
                                                       return self.request('POST', url, data=data, json=json, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 397, in request
                                                       data = resp.json()
                                                              ^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/slyguy.dependencies/resources/modules/requests/models.py", line 910, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
                                                       return _default_decoder.decode(s)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 372, in decode
                                                       obj, end = self.raw_decode(s)
                                                                  ^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 402, in raw_decode
                                                       return self.scan_once(s, idx=_w(s, idx).end())
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-09-26 11:59:08.875 T:524664    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.foxtel.go/?_=play&id=3889324&media_type=1&_is_live=1&_noresume=.pvr
2023-09-26 11:59:10.291 T:3738883   error <general>: plugin.video.foxtel.go - Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 115, in dispatch
                                                       function(**params)
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 59, in decorated_function
                                                       item = f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 50, in decorated_function
                                                       return f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/plugin.py", line 432, in play
                                                       return _play(media_type, id)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/plugin.py", line 435, in _play
                                                       url, license_url = api.play(media_type, id)
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/api.py", line 309, in play
                                                       self._refresh_token()
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/api.py", line 42, in _refresh_token
                                                       data = self._session.post('/auth.class.api.php/logon/{site_id}'.format(site_id=VOD_SITEID), data=payload)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/slyguy.dependencies/resources/modules/requests/sessions.py", line 577, in post
                                                       return self.request('POST', url, data=data, json=json, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 397, in request
                                                       data = resp.json()
                                                              ^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/slyguy.dependencies/resources/modules/requests/models.py", line 910, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
                                                       return _default_decoder.decode(s)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 372, in decode
                                                       obj, end = self.raw_decode(s)
                                                                  ^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 402, in raw_decode
                                                       return self.scan_once(s, idx=_w(s, idx).end())
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-09-26 11:59:13.634 T:525815    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList Playlist Loaded - 9 (ms)
2023-09-26 11:59:13.634 T:525815    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList - Loaded 155 channels.
2023-09-26 11:59:13.634 T:525815    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList - Loaded 0 channel groups.
2023-09-26 11:59:13.634 T:525815    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList - Loaded 0 providers.
2023-09-26 11:59:13.634 T:525815    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList - Loaded 0 media items.
2023-09-26 11:59:13.635 T:525815    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadChannelEpgs - Loaded '3' EPG channels.
2023-09-26 11:59:13.637 T:525815    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEpgEntries - Loaded '0' EPG entries.
2023-09-26 11:59:13.637 T:525815    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEPG - EPG Loaded - 2 (ms)
2023-09-26 11:59:14.126 T:524664    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.foxtel.go/?_=play&id=3889324&media_type=1&_is_live=1&_noresume=.pvr
2023-09-26 11:59:14.542 T:525850    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadChannelEpgs - Loaded '3' EPG channels.
2023-09-26 11:59:14.543 T:525850    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEpgEntries - Loaded '495' EPG entries.
2023-09-26 11:59:14.543 T:525850    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEPG - EPG Loaded - 1 (ms)
2023-09-26 11:59:15.631 T:3738883   error <general>: plugin.video.foxtel.go - Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 115, in dispatch
                                                       function(**params)
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 59, in decorated_function
                                                       item = f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 50, in decorated_function
                                                       return f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/plugin.py", line 432, in play
                                                       return _play(media_type, id)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/plugin.py", line 435, in _play
                                                       url, license_url = api.play(media_type, id)
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/api.py", line 309, in play
                                                       self._refresh_token()
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/api.py", line 42, in _refresh_token
                                                       data = self._session.post('/auth.class.api.php/logon/{site_id}'.format(site_id=VOD_SITEID), data=payload)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/slyguy.dependencies/resources/modules/requests/sessions.py", line 577, in post
                                                       return self.request('POST', url, data=data, json=json, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 397, in request
                                                       data = resp.json()
                                                              ^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/slyguy.dependencies/resources/modules/requests/models.py", line 910, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
                                                       return _default_decoder.decode(s)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 372, in decode
                                                       obj, end = self.raw_decode(s)
                                                                  ^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 402, in raw_decode
                                                       return self.scan_once(s, idx=_w(s, idx).end())
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-09-26 11:59:17.805 T:524664    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.foxtel.go/?_=play&id=3889324&media_type=1&_is_live=1&_noresume=.pvr
2023-09-26 11:59:19.218 T:3738883   error <general>: plugin.video.foxtel.go - Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 115, in dispatch
                                                       function(**params)
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 59, in decorated_function
                                                       item = f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 50, in decorated_function
                                                       return f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/plugin.py", line 432, in play
                                                       return _play(media_type, id)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/plugin.py", line 435, in _play
                                                       url, license_url = api.play(media_type, id)
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/api.py", line 309, in play
                                                       self._refresh_token()
                                                     File "/home/liam/.kodi/addons/plugin.video.foxtel.go/resources/lib/api.py", line 42, in _refresh_token
                                                       data = self._session.post('/auth.class.api.php/logon/{site_id}'.format(site_id=VOD_SITEID), data=payload)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/slyguy.dependencies/resources/modules/requests/sessions.py", line 577, in post
                                                       return self.request('POST', url, data=data, json=json, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 397, in request
                                                       data = resp.json()
                                                              ^^^^^^^^^^^
                                                     File "/home/liam/.kodi/addons/slyguy.dependencies/resources/modules/requests/models.py", line 910, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
                                                       return _default_decoder.decode(s)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 372, in decode
                                                       obj, end = self.raw_decode(s)
                                                                  ^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 402, in raw_decode
                                                       return self.scan_once(s, idx=_w(s, idx).end())
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-09-26 11:59:21.517 T:524664    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.foxtel.go/?_=play&id=2119802&media_type=1&_is_live=1&_noresume=.pvr
2023-09-26 11:59:22.314 T:3738883    info <general>: plugin.video.foxtel.go - Widevine Current MD5: b7a8561d725d43e65e0f64415c702c33
2023-09-26 11:59:22.321 T:524664    info <general>: VideoPlayer::OpenFile: pvr://channels/tv/All%20channels/1@pvr.iptvsimple_746753412.pvr
2023-09-26 11:59:22.322 T:3739308 warning <general>: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
2023-09-26 11:59:22.322 T:3739308    info <general>: Creating InputStream```

**Comment by matthuisman** [comment]
it should do 4x attempts. hard to tell from partial log

**Comment by liam8888999** [comment]
Did you want the full log?

**Comment by matthuisman** [comment]
yes please :)

**Comment by liam8888999** [comment]
https://pastebin.com/iravgfuz  i can do another one if you need where i keep trying until the channel opens but this one is just until the error

**Comment by matthuisman** [comment]
are you able to turn on debug logging please?
are you physically in australia?

**Comment by liam8888999** [comment]
Yes for both

**Comment by liam8888999** [comment]
debug log     https://pastebin.com/AKj0HcJe

**Comment by matthuisman** [comment]
sorry. i meant enable "debug logging" in kodi logging settings and then provide that log.
Itll have much more info

**Comment by liam8888999** [comment]
I did. Maybe I was meant to restart afterwards

**Comment by liam8888999** [comment]
I have debug logging on but I can't seem to get it on the log

**Comment by liam8888999** [comment]
Finally got it https://pastebin.mozilla.org/pfBSyViV

**Comment by liam8888999** [comment]
it looks as though possibly retries are set at 2 rather than 4. https://github.com/matthuisman/slyguy.addons/blob/743e834049a4f512c0f9eb0c548633a4f3afb6ea/plugin.video.foxtel.go/resources/lib/api.py#L20 I tried it set to 4 manually in the code and while I did still see some errors it was no where near as frequent. I will keep experimenting to try and find the ideal amount

**Comment by liam8888999** [comment]
Still seeing the issue when set at 6. It is less frequent though but unfortunately seems random when it happens and the amount of retries it needs

**Comment by liam8888999** [comment]
i trie everywhere ranging from 4 onwards, 9 i was still getting errors, 10 nothing

**Comment by liam8888999** [comment]
i think it might not necesarily be the retry that is making the difference but possibly the time gap between the first and the last is triggering something

**Comment by girkers** [comment]
I got a error when trying to watch "live tv" and on the third attempt it worked.

**Comment by austreams** [comment]
usually if you have a valid _abck cookie from akamai it will leave you alone

**Comment by matthuisman** [comment]
There android apps don't use that though. So Im trying to mimic them

**Comment by austreams** [comment]
you’re right just checked IOS version. so there’s no akamai cookie on the apple app either so then simply has to be header order or tls that’s the only other checks the WAF does.

**Comment by austreams** [comment]
use the same tls ciphers as the android app and you shouldn’t have a problem?

**Comment by matthuisman** [comment]
I am doing that for kayo. Not sure about Foxtel. Might need to check the app

It also can be just using the different headers for the different end
points. I usually just use single headers for all. But there apps may be 3
different depending on which endpoints calling

**Comment by liam8888999** [comment]
The channels were working after a few tries, today I can't even access them at all after multiple tries for some reason

**Comment by MylesFreeman** [comment]
> The channels were working after a few tries, today I can't even access them at all after multiple tries for some reason

Yeah it coming up with Access Denied error again. 🥹

**Comment by matthuisman** [comment]
replacing this issue with https://github.com/matthuisman/slyguy.addons/issues/586
