### ISSUE TITLE
Lots of log spam errors when Sheild goes to sleep

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#573]
Suspect the internet stops when sleeps but Kodi services keep running and therefore dns fails

```
2023-09-25 22:38:13.880 T:13520    info <general>: CWinSystemAndroid::DestroyWindow
2023-09-25 22:38:14.325 T:13435    info <general>: CPeripheralBusAndroid: input device "Logitech K400" with ID 6 updated
2023-09-25 22:38:14.736 T:13435    info <general>: Got device sleep intent
2023-09-25 22:38:14.824 T:13520    info <general>: OnSleep: Running sleep jobs
2023-09-25 22:38:14.848 T:13520    info <general>: PumpPowerEvents: OnSleep called
2023-09-25 22:58:00.429 T:13598   error <general>: script.module.slyguy - HTTPSConnectionPool(host='slyguy.uk', port=443): Max retries exceeded with url: /.repo/addons.xml.md5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x23193a43c0>: Failed to establish a new connection: [Errno 7] No address associated with hostname'))
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 261, in getaddrinfo
                                                       addresses = orig_getaddrinfo(host, port, socket.AF_INET, _type, proto, flags)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/socket.py", line 962, in getaddrinfo
                                                       for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   socket.gaierror: [Errno 7] No address associated with hostname
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/urllib3/connection.py", line 174, in _new_conn
                                                       conn = connection.create_connection(
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/urllib3/util/connection.py", line 72, in create_connection
                                                       for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 263, in getaddrinfo
                                                       addresses = orig_getaddrinfo(host, port, socket.AF_INET6, _type, proto, flags)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/socket.py", line 962, in getaddrinfo
                                                       for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   socket.gaierror: [Errno 7] No address associated with hostname
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/urllib3/connectionpool.py", line 704, in urlopen
                                                       httplib_response = self._make_request(
                                                                          ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/urllib3/connectionpool.py", line 386, in _make_request
                                                       self._validate_conn(conn)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/urllib3/connectionpool.py", line 1041, in _validate_conn
                                                       conn.connect()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/urllib3/connection.py", line 358, in connect
                                                       self.sock = conn = self._new_conn()
                                                                          ^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/urllib3/connection.py", line 186, in _new_conn
                                                       raise NewConnectionError(
                                                   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x23193a43c0>: Failed to establish a new connection: [Errno 7] No address associated with hostname
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/requests/adapters.py", line 440, in send
                                                       resp = conn.urlopen(
                                                              ^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/urllib3/connectionpool.py", line 786, in urlopen
                                                       retries = retries.increment(
                                                                 ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/urllib3/util/retry.py", line 592, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='slyguy.uk', port=443): Max retries exceeded with url: /.repo/addons.xml.md5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x23193a43c0>: Failed to establish a new connection: [Errno 7] No address associated with hostname'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 312, in request
                                                       result = super(RawSession, self).request(method, session_data['url'], **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/requests/sessions.py", line 529, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/requests/sessions.py", line 645, in send
                                                       r = adapter.send(request, **kwargs)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/requests/adapters.py", line 519, in send
                                                       raise ConnectionError(e, request=request)
                                                   requests.exceptions.ConnectionError: HTTPSConnectionPool(host='slyguy.uk', port=443): Max retries exceeded with url: /.repo/addons.xml.md5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x23193a43c0>: Failed to establish a new connection: [Errno 7] No address associated with hostname'))
2023-09-25 22:58:01.521 T:13598   error <general>: script.module.slyguy - HTTPSConnectionPool(host='slyguy.uk', port=443): Max retries exceeded with url: /.repo/addons.xml.md5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x231ac23c70>: Failed to establish a new connection: [Errno 7] No address associated with hostname'))
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 261, in getaddrinfo
                                                       addresses = orig_getaddrinfo(host, port, socket.AF_INET, _type, proto, flags)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/socket.py", line 962, in getaddrinfo
                                                       for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   socket.gaierror: [Errno 7] No address associated with hostname
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/slyguy.dependencies/resources/modules/urllib3/connection.py", line 174, in _new_conn
                                                       conn = connection.create_connection(
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android...
```

**Comment by ksooo** [comment]
Any chance for a fix soon?

**Comment by matthuisman** [comment]
[script.module.slyguy -> v0.74.1](https://github.com/matthuisman/slyguy.addons/commit/d1deaddf4f872ad42460e4054ef178fc96a1ac11) should resolve this. it now simply debug logs a one liner message if the service loop fails

**Comment by ksooo** [comment]
Unfortunately no change. I double-checked that I actually use 0.74.1.

**Comment by matthuisman** [comment]
ok. hopefully  0.74.2 sorts this :)

**Comment by ksooo** [comment]
Confirming fixed. Thanks.

**Comment by matthuisman** [comment]
im going to keep this open.
thought about it more and i do want the logging from the requests exceptions.
so think maybe my loop in the service should instead check for internet and then skip its other stuff if none available
