### ISSUE TITLE
Paramount+ Live streams not working (they've changed how they work again)

### ISSUE THREAD

**Issue by garethlvjones** [matthuisman/slyguy.addons#595]
Couldn't see a (current) issue raised for this. Paramount+ have changed the way live streaming works for football stuff and the extension doesn't seem to be able to work for live streams anymore. 

Vod stuff seems fine though, just live streams

Not sure how to get log file from tv, but here's a pic in case that helps
![kodi-paramountplus](https://github.com/matthuisman/slyguy.addons/assets/28779937/6e1ff76b-e255-465f-b4fb-d9fc0e09024a)

**Comment by scottydulton** [comment]
2023-10-21 18:32:06.563 T:14000   debug <general>: CPlayerGUIInfo::InitCurrentItem(plugin://slyguy.paramount.plus/?_=play_channel&_play=1&listing_id=1257&slug=a-league-men&_is_live=1&_noresume=.pvr)
2023-10-21 18:32:06.563 T:7696    debug <general>: Curl::Debug - TEXT: Connected to 127.0.0.1 (127.0.0.1) port 52103 (#28)
2023-10-21 18:32:06.563 T:7696    debug <general>: Curl::Debug - HEADER_OUT: GET /https://propeah44e9b.airspace-cdn.cbsivideo.com/out/v1/737bc585584c4cea832a915327fbfb6e/start/1697867100/manifest.mpd HTTP/1.1
2023-10-21 18:32:06.563 T:7696    debug <general>: Curl::Debug - HEADER_OUT: Host: 127.0.0.1:52103
2023-10-21 18:32:06.563 T:7696    debug <general>: Curl::Debug - HEADER_OUT: User-Agent: Kodi/20.1 (Windows NT 10.0.19045.3570; Win64; x64) App_Bitness/64 Version/20.1-(20.1.0)-Git:20230312-289ec664e3
2023-10-21 18:32:06.563 T:7696    debug <general>: Curl::Debug - HEADER_OUT: Accept: */*
2023-10-21 18:32:06.563 T:7696    debug <general>: Curl::Debug - HEADER_OUT: Accept-Encoding: gzip
2023-10-21 18:32:06.563 T:7696    debug <general>: Curl::Debug - HEADER_OUT: Accept-Charset: UTF-8,*;q=0.8
2023-10-21 18:32:06.563 T:7696    debug <general>: Curl::Debug - HEADER_OUT: authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjNkNjg4NGJmLWViMDktNDA1Zi1hOWZjLWU0NGE1NmY3NjZiNiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMjI5MzQ3M19BVSIsImVudCI6W3siYmlkIjoiQWxsQWNjZXNzTWFpbiIsImVwaWQiOjEyfV0sImlhdCI6MTY5Nzg3MzUyNSwiZXhwIjoxNjk3ODg3OTI1LCJpc3MiOiJjYnMiLCJhaWQiOiJjYnNpIiwiaXNlIjp0cnVlLCJqdGkiOiI3N2I1OWJkMi0xMTNhLTQ3ZGItYTMzMS1lZjk0MGY5OTU5NGMifQ.zobW78_-dYB4QDqzuK5N0H3ez_bh8-VrDgM8hbBQcU0
2023-10-21 18:32:06.564 T:15584   debug <general>: script.module.slyguy - REQUEST IN: https://propeah44e9b.airspace-cdn.cbsivideo.com/out/v1/737bc585584c4cea832a915327fbfb6e/start/1697867100/manifest.mpd (GET)
2023-10-21 18:32:06.564 T:15584   debug <general>: script.module.slyguy - Session created from proxy data
2023-10-21 18:32:06.566 T:15584   debug <general>: script.module.slyguy - REQUEST OUT: https://propeah44e9b.airspace-cdn.cbsivideo.com/out/v1/737bc585584c4cea832a915327fbfb6e/start/1697867100/manifest.mpd (GET)
2023-10-21 18:32:06.651 T:15584   debug <general>: script.module.slyguy - SSL Cipher: propeah44e9b.airspace-cdn.cbsivideo.com - ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
2023-10-21 18:32:06.658 T:15584   debug <general>: script.module.slyguy - RESPONSE IN: https://propeah44e9b.airspace-cdn.cbsivideo.com/out/v1/737bc585584c4cea832a915327fbfb6e/start/1697867100/manifest.mpd (200)
2023-10-21 18:32:06.658 T:15584   error <general>: script.module.slyguy - Invalid m3u8
                                                   Traceback (most recent call last):
                                                     File "C:\Users\stimp\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 298, in do_GET
                                                       self._parse_m3u8(response)
                                                     File "C:\Users\stimp\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 1242, in _parse_m3u8
                                                       raise Exception('Invalid m3u8')
                                                   Exception: Invalid m3u8

**Comment by scottydulton** [comment]
@matthuisman would this be a simple fix?

**Comment by liam8888999** [comment]
seems to be getting picked up as m3u rather than mpd possibly?

**Comment by liam8888999** [comment]
im not even close to an expert but possibly the error is with somethings being on the new line here https://github.com/matthuisman/slyguy.addons/blob/0dbaaddcec857c830adc7ac91c19605087dd5833/script.module.slyguy/resources/lib/proxy.py#L311 @matthuisman

**Comment by scottydulton** [comment]
@matthuisman there is a live stream on in paramount now if you have time to have a look :)

**Comment by matthuisman** [comment]
just pushed [slyguy.paramount.plus -> v0.7.3](https://github.com/matthuisman/slyguy.addons/commit/c5e65b1e73cbb1ddc48f57d3d20242bb6c6af401) . please test

**Comment by garethlvjones** [comment]
Legend, working a treat for me now. Thanks for all you do!
