### ISSUE TITLE
Willow TV: unable to play highlights/replays

### ISSUE THREAD

**Issue by vajonam** [matthuisman/slyguy.addons#599]
with the ICC world cup currently on, will nice to be able to play world cup highlights

```
2023-10-24 14:23:36.383 T:419063   DEBUG <general>: script.module.slyguy - SSL Cipher: willowtv-tavod165w.pc.cdn.bitgravity.com - ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
2023-10-24 14:23:36.471 T:419063   DEBUG <general>: script.module.slyguy - RESPONSE IN: https://willowtv-tavod165w.pc.cdn.bitgravity.com/tavod165w/warchives/ICC_Cricket_World_Cup_2023/10248/Highlights/10248_Decock_174runs.mp4/playlist.m3u8?e=1698175414&h=78056abafb4c7c04534b8af7a4db0a55 (403)
2023-10-24 14:23:36.472 T:419063   ERROR <general>: script.module.slyguy - Invalid m3u8
                                                   Traceback (most recent call last):
                                                     File "/home/manojav/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 298, in do_GET
                                                       self._parse_m3u8(response)
                                                     File "/home/manojav/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 1242, in _parse_m3u8
                                                       raise Exception('Invalid m3u8')
                                                   Exception: Invalid m3u8
2023-10-24 14:23:36.472 T:419063   DEBUG <general>: script.module.slyguy - RESPONSE OUT: https://willowtv-tavod165w.pc.cdn.bitgravity.com/tavod165w/warchives/ICC_Cricket_World_Cup_2023/10248/Highlights/10248_Decock_174runs.mp4/playlist.m3u8?e=1698175414&h=78056abafb4c7c04534b8af7a4db0a55 (200)
```

looks like 

```
curl https://willowtv-tavod165w.pc.cdn.bitgravity.com/tavod165w/warchives/ICC_Cricket_World_Cup_2023/10248/Highlights/10248_Decock_174runs.mp4/playlist.m3u8\?e\=1698175414\&h\=78056abafb4c7c04534b8af7a4db0a55
```

returns another M3U8                                                                                                              
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=7929564,CODECS="avc1.4d4029,mp4a.40.2",RESOLUTION=1920x1080
chunklist.m3u8?e=1698258252&h=5856cebfe86257439eadaa94935c02f4
```

and that in turn then loads up the .ts files correctly

```
curl https://willowtv-tavod165w.pc.cdn.bitgravity.com/tavod165w/warchives/ICC_Cricket_World_Cup_2023/10248/Highlights/10248_Decock_174runs.mp4/chunklist.m3u8\?e=1698258252\&h=5856cebfe86257439eadaa94935c02f4
```

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:6.0,
media_0.ts?e=1698258287&h=65d4b5b372eeec242715f6dca21bd609
#EXTINF:7.071,
media_1.ts?e=1698258287&h=8e70384db4fc9d4c1c8adbf36a356729
#EXTINF:6.0,
media_2.ts?e=1698258287&h=d6595f6774c98d4a557f127eb49a38b0
#EXTINF:6.0,
media_3.ts?e=1698258287&h=4faee6093d9c3024e3fb540f405bcd26
#EXTINF:6.0,
media_4.ts?e=1698258287&h=35101380cfc60715f14773c510cb516c
#EXTINF:6.0,
media_5.ts?e=1698258287&h=a810f8d8d8916f7f6ee089c49ba9878e
#EXTINF:6.056,
media_6.ts?e=1698258287&h=5774aa629e72a0e0b3ff211fe8bba654
#EXTINF:6.0,
media_7.ts?e=1698258287&h=a9ffd49de06e8f6b63a976814fa591ab
#EXTINF:6.0,
media_8.ts?e=1698258287&h=9df39335c00583c8131bb011ff877d21
#EXTINF:6.0,
media_9.ts?e=1698258287&h=9f281fcaa3e142871a9166b28ec6b5e7
#EXTINF:6.0,
media_10.ts?e=1698258287&h=e3f9575262e7045c3f023d1a7ede8c38
```

I have changed some of the tokens, I assume they change over time, but just being careful to not compromise my account.

**Comment by matthuisman** [comment]
Issue is the 403 error when the add-on tries to get the playlist. Is your
Kodi instance in the correct location for willow tv??

**Comment by vajonam** [comment]
Yes. I am in Canada. And willow tv is officially available. Works fine on their app. No VPNs or anything.

**Comment by vajonam** [comment]
Why does it work from a curl command on the same box then? Weird.

**Comment by matthuisman** [comment]
Could you try turn off slyguy proxy in the slyguy common settings and then
see if it plays?

**Comment by matthuisman** [comment]
also, would you be willing to share your willow login temporarily so I can test and fix?
if yes, see here: https://www.matthuisman.nz/2018/06/looking-for-logins.html

**Comment by vajonam** [comment]
Yes. I can do that. What Timezone are you in. Since the games are on it only allows one login at a time. So would like it not affect my watching if possible.

**Comment by vajonam** [comment]
Tried turning off the proxy. No dice. Same problem. Look for an email with the credentials.

**Comment by vajonam** [comment]
> also, would you be willing to share your willow login temporarily so I can test and fix? if yes, see here: https://www.matthuisman.nz/2018/06/looking-for-logins.html

@matthuisman You should have an email now.

**Comment by matthuisman** [comment]
thanks. got it :)

it only failed on some matches (eg. world cup)
Should be fixed now with [plugin.video.willow.tv -> v0.1.5](https://github.com/matthuisman/slyguy.addons/commit/913a2a3a830f767060b4d409cc7db5c33906adb7)
