### ISSUE TITLE
HBOMax stopped working

### ISSUE THREAD

**Issue by NH3CL** [matthuisman/slyguy.addons#647]
Hi,

The plugin stopped working on the latest OSMC Raspberry pi 4 build.

`2023-12-22 13:40:51.466 T:496     debug <general>: ------ Window Deinit (Home.xml) ------
2023-12-22 13:40:51.479 T:496     debug <general>: ------ Window Init (MyVideoNav.xml) ------
2023-12-22 13:40:51.492 T:496     error <general>: Control 50 in window 10025 has been asked to focus, but it can't
2023-12-22 13:40:51.500 T:496     debug <general>: started alarm with name: animmulti2
2023-12-22 13:40:51.500 T:496     debug <general>: started alarm with name: themewall
2023-12-22 13:40:51.506 T:10472   debug <general>: ffmpeg[0xc076a960]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2023-12-22 13:40:51.645 T:496     debug <general>: CGUIMediaWindow::GetDirectory (plugin://slyguy.hbo.max/)
2023-12-22 13:40:51.645 T:496     debug <general>:   ParentPath = [plugin://slyguy.hbo.max/]
2023-12-22 13:40:51.647 T:10599   debug <general>: Thread waiting start, auto delete: false
2023-12-22 13:40:51.652 T:10473   debug <general>: CAddonDatabase::SetLastUsed[slyguy.hbo.max] took 6 ms
2023-12-22 13:40:51.654 T:10599   debug <general>: CScriptRunner: running add-on script HBO Max('plugin://slyguy.hbo.max/', '198', '')
2023-12-22 13:40:51.655 T:10600   debug <general>: Thread LanguageInvoker start, auto delete: false
2023-12-22 13:40:51.655 T:10600   debug <general>: initializing python engine.
2023-12-22 13:40:51.655 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): start processing
2023-12-22 13:40:51.728 T:10472   debug <general>: DoWork - took 223 ms to load special://skin/backgrounds/default_bg.jpg
2023-12-22 13:40:51.748 T:496     debug <general>: ------ Window Init (DialogBusy.xml) ------
2023-12-22 13:40:51.819 T:10600   debug <general>: -->Python Interpreter Initialized<--
2023-12-22 13:40:51.819 T:10600   debug <general>:

2023-12-22 13:40:51.820 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): the source file to load is "/home/osmc/.kodi/addons/slyguy.hbo.max/default.py"
2023-12-22 13:40:51.820 T:10600   debug <general>: CPythonInvoker(474): full python path:
2023-12-22 13:40:51.820 T:10600   debug <general>: CPythonInvoker(474):   custom python path:
2023-12-22 13:40:51.820 T:10600   debug <general>: CPythonInvoker(474):     /home/osmc/.kodi/addons/script.module.slyguy/resources/modules
2023-12-22 13:40:51.821 T:10600   debug <general>: CPythonInvoker(474):     /home/osmc/.kodi/addons/slyguy.dependencies/resources/modules
2023-12-22 13:40:51.821 T:10600   debug <general>: CPythonInvoker(474):     /home/osmc/.kodi/addons/slyguy.hbo.max
2023-12-22 13:40:51.821 T:10600   debug <general>: CPythonInvoker(474):   default python path:
2023-12-22 13:40:51.821 T:10600   debug <general>: CPythonInvoker(474):     /usr/lib/python39.zip
2023-12-22 13:40:51.822 T:10600   debug <general>: CPythonInvoker(474):     /usr/lib/python3.9
2023-12-22 13:40:51.822 T:10600   debug <general>: CPythonInvoker(474):     /usr/lib/python3.9/lib-dynload
2023-12-22 13:40:51.822 T:10600   debug <general>: CPythonInvoker(474):     /usr/local/lib/python3.9/dist-packages
2023-12-22 13:40:51.822 T:10600   debug <general>: CPythonInvoker(474):     /usr/lib/python3/dist-packages
2023-12-22 13:40:51.822 T:10600   debug <general>: CPythonInvoker(474): adding args:
2023-12-22 13:40:51.823 T:10600   debug <general>: CPythonInvoker(474):  plugin://slyguy.hbo.max/
2023-12-22 13:40:51.823 T:10600   debug <general>: CPythonInvoker(474):  198
2023-12-22 13:40:51.823 T:10600   debug <general>: CPythonInvoker(474):
2023-12-22 13:40:51.823 T:10600   debug <general>: CPythonInvoker(474):  resume:false
2023-12-22 13:40:51.823 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): entering source directory /home/osmc/.kodi/addons/slyguy.hbo.max
2023-12-22 13:40:51.823 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): instantiating addon using automatically obtained id of "slyguy.hbo.max" dependent on version 0.0.0 of the xbmc.python api
2023-12-22 13:40:52.471 T:10600   debug <general>: slyguy.hbo.max - sys.path: ['/home/osmc/.kodi/addons/script.module.slyguy/resources/modules', '/home/osmc/.kodi/addons/slyguy.dependencies/resources/modules', '/home/osmc/.kodi/addons/slyguy.hbo.max', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages']
2023-12-22 13:40:52.472 T:10600   debug <general>: slyguy.hbo.max - Fixed sys.path: ['/home/osmc/.kodi/addons/slyguy.hbo.max', '/home/osmc/.kodi/addons/script.module.slyguy/resources/modules', '/home/osmc/.kodi/addons/slyguy.dependencies/resources/modules', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages']
2023-12-22 13:40:53.961 T:10600   debug <general>: slyguy.hbo.max - OpenSSL 1.1.1n  15 Mar 2022
2023-12-22 13:40:54.011 T:10600   debug <general>: slyguy.hbo.max - @plugin.plugin_middleware() is deprecated. Use @plugin.plugin_request() instead
2023-12-22 13:40:54.011 T:10600   debug <general>: slyguy.hbo.max - SIGNAL: before_dispatch
2023-12-22 13:40:54.012 T:10600   debug <CAddonSettings[0@slyguy.hbo.max]>: trying to load setting definitions from old format...
2023-12-22 13:40:54.014 T:10600   debug <CSettingsManager>: requested setting (4k_enabled) was not found.
2023-12-22 13:40:54.015 T:10600   debug <CAddonSettings[0@script.module.slyguy]>: trying to load setting definitions from old format...
2023-12-22 13:40:54.016 T:10600   debug <CSettingsManager>: requested setting (_addon_md5) was not found.
2023-12-22 13:40:54.016 T:10600   debug <CSettingsManager>: requested setting (_arch) was not found.
2023-12-22 13:40:54.016 T:10600   debug <CSettingsManager>: requested setting (_last_updates_check) was not found.
2023-12-22 13:40:54.016 T:10600   debug <CSettingsManager>: requested setting (_mac) was not found.
2023-12-22 13:40:54.016 T:10600   debug <CSettingsManager>: requested setting (_updates) was not found.
2023-12-22 13:40:54.016 T:10600   debug <CSettingsManager>: requested setting (_wv_last_check) was not found.
2023-12-22 13:40:54.016 T:10600   debug <CSettingsManager>: requested setting (_wv_latest_hash) was not found.
2023-12-22 13:40:54.016 T:10600   debug <CSettingsManager>: requested setting (show_series_folders) was not found.
2023-12-22 13:40:54.017 T:10600   debug <CSettingsManager>: requested setting (video_folder_content) was not found.
2023-12-22 13:40:54.019 T:10600   debug <general>: slyguy.hbo.max - Cache data loaded
2023-12-22 13:40:54.021 T:10600   debug <general>: slyguy.hbo.max - Router Parsed: '' => index {'_url': ''}
2023-12-22 13:40:54.031 T:10600   debug <general>: slyguy.hbo.max - SIGNAL: after_dispatch
2023-12-22 13:40:54.032 T:10599   debug <general>: Thread waiting 3429888256 terminating
2023-12-22 13:40:54.035 T:10600   debug <general>: slyguy.hbo.max - SIGNAL: on_close
2023-12-22 13:40:54.036 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): script successfully run
2023-12-22 13:40:54.045 T:496     debug <general>: ------ Window Deinit (DialogBusy.xml) ------
2023-12-22 13:40:54.049 T:10601   debug <general>: Thread BackgroundLoader start, auto delete: false
2023-12-22 13:40:54.059 T:10601   debug <general>: Thread BackgroundLoader 3053023488 terminating
2023-12-22 13:40:54.066 T:10473   debug <general>: ffmpeg[0xba81fb80]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2023-12-22 13:40:54.076 T:10473   debug <general>: ffmpeg[0xba81fb80]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
2023-12-22 13:40:54.078 T:10475   debug <general>: ffmpeg[0x87f73e0]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2023-12-22 13:40:54.081 T:10475   debug <general>: ffmpeg[0x87f73e0]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
2023-12-22 13:40:54.147 T:496     debug <general>: ------ Window Init (custom_1171_AuxMultiSort.xml) ------
2023-12-22 13:40:55.591 T:573     debug <general>: BUTTON [ 0 ] on "Logitech Gamepad F710" pressed
2023-12-22 13:40:55.591 T:573     debug <general>: FEATURE [ a ] on game.controller.default pressed (ignored)
2023-12-22 13:40:55.593 T:496     debug <general>: Skipped 1 duplicate messages..
2023-12-22 13:40:55.593 T:496     debug <general>: ------ Window Deinit (custom_1171_AuxMultiSort.xml) ------
2023-12-22 13:40:55.717 T:573     debug <general>: BUTTON [ 0 ] on "Logitech Gamepad F710" released
2023-12-22 13:40:55.717 T:573     debug <general>: FEATURE [ a ] on game.controller.default released
2023-12-22 13:40:55.729 T:496     debug <general>: Skipped 1 duplicate messages..
2023-12-22 13:40:55.729 T:496     debug <general>: CGUIMediaWindow::GetDirectory (plugin://slyguy.hbo.max/?_=page&label=Kiemelt&slug=urn%3ahbo%3apage%3ahome)
2023-12-22 13:40:55.729 T:496     debug <general>:   ParentPath = [plugin://slyguy.hbo.max/]
2023-12-22 13:40:55.731 T:10602   debug <general>: Thread waiting start, auto delete: false
2023-12-22 13:40:55.737 T:10474   debug <general>: CAddonDatabase::SetLastUsed[slyguy.hbo.max] took 7 ms
2023-12-22 13:40:55.737 T:10602   debug <general>: CScriptRunner: running add-on script HBO Max('plugin://slyguy.hbo.max/', '198', '?_=page&label=Kiemelt&slug=urn%3ahbo%3apage%3ahome')
2023-12-22 13:40:55.737 T:10602   debug <general>: GetLanguageInvoker - Reusing LanguageInvokerThread 474 for script /home/osmc/.kodi/addons/slyguy.hbo.max/default.py
2023-12-22 13:40:55.737 T:10600   debug <general>: initializing python engine.
2023-12-22 13:40:55.737 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): start processing
2023-12-22 13:40:55.738 T:10600   debug <general>: CPythonInvoker(474): adding args:
2023-12-22 13:40:55.738 T:10600   debug <general>: CPythonInvoker(474):  plugin://slyguy.hbo.max/
2023-12-22 13:40:55.738 T:10600   debug <general>: CPythonInvoker(474):  198
2023-12-22 13:40:55.738 T:10600   debug <general>: CPythonInvoker(474):  ?_=page&label=Kiemelt&slug=urn%3ahbo%3apage%3ahome
2023-12-22 13:40:55.738 T:10600   debug <general>: CPythonInvoker(474):  resume:false
2023-12-22 13:40:55.738 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): entering source directory /home/osmc/.kodi/addons/slyguy.hbo.max
2023-12-22 13:40:55.738 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): instantiating addon using automatically obtained id of "slyguy.hbo.max" dependent on version 0.0.0 of the xbmc.python api
2023-12-22 13:40:55.739 T:10600   debug <general>: slyguy.hbo.max - SIGNAL: before_dispatch
2023-12-22 13:40:55.740 T:10600   debug <CAddonSettings[0@slyguy.hbo.max]>: trying to load setting definitions from old format...
2023-12-22 13:40:55.741 T:10600   debug <CSettingsManager>: requested setting (4k_enabled) was not found.
2023-12-22 13:40:55.743 T:10600   debug <CAddonSettings[0@script.module.slyguy]>: trying to load setting definitions from old format...
2023-12-22 13:40:55.744 T:10600   debug <CSettingsManager>: requested setting (_addon_md5) was not found.
2023-12-22 13:40:55.744 T:10600   debug <CSettingsManager>: requested setting (_arch) was not found.
2023-12-22 13:40:55.744 T:10600   debug <CSettingsManager>: requested setting (_last_updates_check) was not found.
2023-12-22 13:40:55.744 T:10600   debug <CSettingsManager>: requested setting (_mac) was not found.
2023-12-22 13:40:55.744 T:10600   debug <CSettingsManager>: requested setting (_updates) was not found.
2023-12-22 13:40:55.744 T:10600   debug <CSettingsManager>: requested setting (_wv_last_check) was not found.
2023-12-22 13:40:55.745 T:10600   debug <CSettingsManager>: requested setting (_wv_latest_hash) was not found.
2023-12-22 13:40:55.745 T:10600   debug <CSettingsManager>: requested setting (show_series_folders) was not found.
2023-12-22 13:40:55.745 T:10600   debug <CSettingsManager>: requested setting (video_folder_content) was not found.
2023-12-22 13:40:55.745 T:10600   debug <general>: slyguy.hbo.max - Cache data loaded
2023-12-22 13:40:55.748 T:10600   debug <general>: slyguy.hbo.max - Router Parsed: 'plugin://slyguy.hbo.max/?_=page&label=Kiemelt&slug=urn%3ahbo%3apage%3ahome' => page {'label': 'Kiemelt', 'slug': 'urn:hbo:page:home', '_url': 'plugin://slyguy.hbo.max/?_=page&label=Kiemelt&slug=urn%3ahbo%3apage%3ahome'}
2023-12-22 13:40:55.749 T:10600   debug <general>: slyguy.hbo.max - GUEST CONFIG
2023-12-22 13:40:55.831 T:496     debug <general>: ------ Window Init (DialogBusy.xml) ------
2023-12-22 13:40:55.834 T:10600   debug <general>: slyguy.hbo.max - System: Linux, Arch: armv7
2023-12-22 13:40:55.834 T:10600   debug <general>: slyguy.hbo.max - Attempt 1/2: POST https://oauth.api.hbo.com/auth/tokens
2023-12-22 13:40:55.899 T:10600   debug <general>: slyguy.hbo.max - SSL Cipher: oauth.api.hbo.com - ('TLS_AES_128_GCM_SHA256', 'TLSv1.3', 128)
2023-12-22 13:40:56.075 T:10600   debug <general>: slyguy.hbo.max - Attempt 1/2: POST https://sessions.api.hbo.com/sessions/v1/clientConfig
2023-12-22 13:40:56.123 T:10600   debug <general>: slyguy.hbo.max - SSL Cipher: sessions.api.hbo.com - ('TLS_AES_128_GCM_SHA256', 'TLSv1.3', 128)
2023-12-22 13:40:56.211 T:10600   debug <general>: slyguy.hbo.max - Cache Set: config
2023-12-22 13:40:56.212 T:10600   debug <general>: slyguy.hbo.max - Attempt 1/2: POST https://oauth-emea.api.hbo.com/auth/tokens
2023-12-22 13:40:56.262 T:10600   debug <general>: slyguy.hbo.max - SSL Cipher: oauth-emea.api.hbo.com - ('TLS_AES_128_GCM_SHA256', 'TLSv1.3', 128)
2023-12-22 13:40:56.305 T:10600   debug <general>: slyguy.hbo.max - SIGNAL: on_error
2023-12-22 13:40:56.305 T:10600   debug <general>: slyguy.hbo.max - Mem Cache: Deleted 1 Rows
2023-12-22 13:40:56.306 T:10600   debug <general>: slyguy.hbo.max - SIGNAL: on_close
2023-12-22 13:40:56.309 T:10600   debug <general>: slyguy.hbo.max - API kérési hiba
                                                   Szerver Hiba: An unknown problem occurred. Please contact your TV provider.
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 41, in throwable
                                                       yield
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 115, in dispatch
                                                       function(**params)
                                                     File "/home/osmc/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 59, in decorated_function
                                                       item = f(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/slyguy.hbo.max/resources/lib/plugin.py", line 312, in page
                                                       data = api.express_content(slug, tab=tab)
                                                     File "/home/osmc/.kodi/addons/slyguy.hbo.max/resources/lib/api.py", line 335, in express_content
                                                       self._refresh_token()
                                                     File "/home/osmc/.kodi/addons/slyguy.hbo.max/resources/lib/api.py", line 45, in _refresh_token
                                                       self._oauth_token(payload, {'Authorization': None})
                                                     File "/home/osmc/.kodi/addons/slyguy.hbo.max/resources/lib/api.py", line 76, in _oauth_token
                                                       self._check_errors(data)
                                                     File "/home/osmc/.kodi/addons/slyguy.hbo.max/resources/lib/api.py", line 204, in _check_errors
                                                       raise APIError(_(error, msg=error_msg))
                                                   resources.lib.api.APIError: API kérési hiba
                                                   Szerver Hiba: An unknown problem occurred. Please contact your TV provider.
2023-12-22 13:40:56.313 T:496     debug <general>: ------ Window Init (DialogConfirm.xml) ------
2023-12-22 13:40:58.597 T:496     debug <general>: ------ Window Init (custom_1171_AuxMultiSort.xml) ------
2023-12-22 13:40:59.929 T:496     debug <general>: CheckIdle - Closing session to http://www.msftconnecttest.com (easy=0xc1f11e60, multi=0x0)
2023-12-22 13:41:03.598 T:496     debug <general>: ------ Window Init (custom_1174_AuxMultiWall.xml) ------
2023-12-22 13:41:04.786 T:573     debug <general>: BUTTON [ 0 ] on "Logitech Gamepad F710" pressed
2023-12-22 13:41:04.786 T:573     debug <general>: FEATURE [ a ] on game.controller.default pressed (ignored)
2023-12-22 13:41:04.797 T:496     debug <general>: Skipped 1 duplicate messages..
2023-12-22 13:41:04.797 T:496     debug <general>: ------ Window Deinit (custom_1171_AuxMultiSort.xml) ------
2023-12-22 13:41:04.798 T:496     debug <general>: ------ Window Deinit (custom_1174_AuxMultiWall.xml) ------
2023-12-22 13:41:04.866 T:573     debug <general>: BUTTON [ 0 ] on "Logitech Gamepad F710" released
2023-12-22 13:41:04.866 T:573     debug <general>: FEATURE [ a ] on game.controller.default released
2023-12-22 13:41:05.033 T:496     debug <general>: Skipped 1 duplicate messages..
2023-12-22 13:41:05.033 T:496     debug <general>: ------ Window Deinit (DialogConfirm.xml) ------
2023-12-22 13:41:05.045 T:10602   error <general>: GetDirectory - Error getting plugin://slyguy.hbo.max/?_=page&label=Kiemelt&slug=urn%3ahbo%3apage%3ahome
2023-12-22 13:41:05.046 T:10602   debug <general>: Thread waiting 3429888256 terminating
2023-12-22 13:41:05.046 T:10600   debug <general>: slyguy.hbo.max - SIGNAL: after_dispatch
2023-12-22 13:41:05.050 T:10600   debug <general>: slyguy.hbo.max - SIGNAL: on_close
2023-12-22 13:41:05.050 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): script successfully run
2023-12-22 13:41:05.062 T:496     debug <general>: ------ Window Deinit (DialogBusy.xml) ------
2023-12-22 13:41:05.063 T:496     error <general>: CGUIMediaWindow::GetDirectory(plugin://slyguy.hbo.max/?_=page&label=Kiemelt&slug=urn%3ahbo%3apage%3ahome) failed
2023-12-22 13:41:05.063 T:496     debug <general>: CGUIMediaWindow::GetDirectory (plugin://slyguy.hbo.max/)
2023-12-22 13:41:05.063 T:496     debug <general>:   ParentPath = [plugin://]
2023-12-22 13:41:05.064 T:10603   debug <general>: Thread waiting start, auto delete: false
2023-12-22 13:41:05.069 T:10475   debug <general>: CAddonDatabase::SetLastUsed[slyguy.hbo.max] took 5 ms
2023-12-22 13:41:05.069 T:10603   debug <general>: CScriptRunner: running add-on script HBO Max('plugin://slyguy.hbo.max/', '198', '')
2023-12-22 13:41:05.069 T:10603   debug <general>: GetLanguageInvoker - Reusing LanguageInvokerThread 474 for script /home/osmc/.kodi/addons/slyguy.hbo.max/default.py
2023-12-22 13:41:05.069 T:10600   debug <general>: initializing python engine.
2023-12-22 13:41:05.070 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): start processing
2023-12-22 13:41:05.070 T:10600   debug <general>: CPythonInvoker(474): adding args:
2023-12-22 13:41:05.070 T:10600   debug <general>: CPythonInvoker(474):  plugin://slyguy.hbo.max/
2023-12-22 13:41:05.070 T:10600   debug <general>: CPythonInvoker(474):  198
2023-12-22 13:41:05.070 T:10600   debug <general>: CPythonInvoker(474):
2023-12-22 13:41:05.070 T:10600   debug <general>: CPythonInvoker(474):  resume:false
2023-12-22 13:41:05.070 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): entering source directory /home/osmc/.kodi/addons/slyguy.hbo.max
2023-12-22 13:41:05.070 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): instantiating addon using automatically obtained id of "slyguy.hbo.max" dependent on version 0.0.0 of the xbmc.python api
2023-12-22 13:41:05.071 T:10600   debug <general>: slyguy.hbo.max - SIGNAL: before_dispatch
2023-12-22 13:41:05.072 T:10600   debug <CAddonSettings[0@slyguy.hbo.max]>: trying to load setting definitions from old format...
2023-12-22 13:41:05.074 T:10600   debug <CSettingsManager>: requested setting (4k_enabled) was not found.
2023-12-22 13:41:05.075 T:10600   debug <CAddonSettings[0@script.module.slyguy]>: trying to load setting definitions from old format...
2023-12-22 13:41:05.076 T:10600   debug <CSettingsManager>: requested setting (_addon_md5) was not found.
2023-12-22 13:41:05.076 T:10600   debug <CSettingsManager>: requested setting (_arch) was not found.
2023-12-22 13:41:05.076 T:10600   debug <CSettingsManager>: requested setting (_last_updates_check) was not found.
2023-12-22 13:41:05.076 T:10600   debug <CSettingsManager>: requested setting (_mac) was not found.
2023-12-22 13:41:05.076 T:10600   debug <CSettingsManager>: requested setting (_updates) was not found.
2023-12-22 13:41:05.077 T:10600   debug <CSettingsManager>: requested setting (_wv_last_check) was not found.
2023-12-22 13:41:05.077 T:10600   debug <CSettingsManager>: requested setting (_wv_latest_hash) was not found.
2023-12-22 13:41:05.077 T:10600   debug <CSettingsManager>: requested setting (show_series_folders) was not found.
2023-12-22 13:41:05.077 T:10600   debug <CSettingsManager>: requested setting (video_folder_content) was not found.
2023-12-22 13:41:05.078 T:10600   debug <general>: slyguy.hbo.max - Cache data loaded
2023-12-22 13:41:05.079 T:10600   debug <general>: slyguy.hbo.max - Router Parsed: '' => index {'_url': ''}
2023-12-22 13:41:05.088 T:10600   debug <general>: slyguy.hbo.max - SIGNAL: after_dispatch
2023-12-22 13:41:05.089 T:10603   debug <general>: Thread waiting 3429888256 terminating
2023-12-22 13:41:05.089 T:10600   debug <general>: slyguy.hbo.max - SIGNAL: on_close
2023-12-22 13:41:05.089 T:10600   debug <general>: CPythonInvoker(474, /home/osmc/.kodi/addons/slyguy.hbo.max/default.py): script successfully run
2023-12-22 13:41:05.092 T:10604   debug <general>: Thread BackgroundLoader start, auto delete: false
2023-12-22 13:41:05.101 T:10604   debug <general>: Thread BackgroundLoader 3053023488 terminating
`

**Comment by matthuisman** [comment]
https://github.com/matthuisman/slyguy.addons/issues/454
