### ISSUE TITLE
AU Freeview - Invalid m3u8

### ISSUE THREAD

**Issue by AndrewElz** [matthuisman/slyguy.addons#671]
When I try to play SBS channels using the AU freeview addon, an error is thrown (ABC channels are OK):

2024-01-28 15:24:25.253 T:5564     info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.au.freeview/?_=play&region=Sydney&slug=mjh-sbs-viceland&_is_live=1&_noresume=.pvr
2024-01-28 15:24:26.184 T:5564     info <general>: VideoPlayer::OpenFile: pvr://channels/tv/All%20channels/1@pvr.iptvsimple_1446063572.pvr
2024-01-28 15:24:26.186 T:19313    info <general>: Creating InputStream
2024-01-28 15:24:26.189 T:19313    info <general>: Creating Demuxer
2024-01-28 15:24:26.481 T:19314   error <general>: script.module.slyguy - Invalid m3u8
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 298, in do_GET
                                                       self._parse_m3u8(response)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 1250, in _parse_m3u8
                                                       raise Exception('Invalid m3u8')
                                                   Exception: Invalid m3u8
2024-01-28 15:24:27.147 T:19313    info <general>: Skipped 1 duplicate messages..
2024-01-28 15:24:27.147 T:19313    info <general>: Process - eof reading from demuxer
2024-01-28 15:24:27.148 T:19313    info <general>: CVideoPlayer::OnExit()
2024-01-28 15:24:27.148 T:19313    info <general>: VideoPlayer: eof, waiting for queues to empty
2024-01-28 15:24:27.163 T:19253    info <general>: Deleting settings information for files pvr://channels/tv/All%20channels/1@pvr.iptvsimple_1446063572.pvr
2024-01-28 15:24:27.208 T:5564     info <general>: CVideoPlayer::CloseFile()
2024-01-28 15:24:27.217 T:5564     info <general>: VideoPlayer: waiting for threads to exit
2024-01-28 15:24:27.218 T:5564     info <general>: VideoPlayer: finished waiting
2024-01-28 15:24:27.218 T:5564     info <general>: CVideoPlayer::CloseFile()
2024-01-28 15:24:27.218 T:5564     info <general>: VideoPlayer: waiting for threads to exit
2024-01-28 15:24:27.218 T:5564     info <general>: VideoPlayer: finished waiting
2024-01-28 15:24:39.762 T:5564     info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.au.freeview/?_=play&region=Sydney&slug=mjh-sbs&_is_live=1&_noresume=.pvr
2024-01-28 15:24:39.931 T:5564     info <general>: VideoPlayer::OpenFile: pvr://channels/tv/All%20channels/1@pvr.iptvsimple_1660689061.pvr
2024-01-28 15:24:39.933 T:19328    info <general>: Creating InputStream
2024-01-28 15:24:39.935 T:19328    info <general>: Creating Demuxer
2024-01-28 15:24:39.997 T:19329   error <general>: script.module.slyguy - Invalid m3u8
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 298, in do_GET
                                                       self._parse_m3u8(response)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 1250, in _parse_m3u8
                                                       raise Exception('Invalid m3u8')
                                                   Exception: Invalid m3u8
2024-01-28 15:24:40.600 T:19328    info <general>: Skipped 1 duplicate messages..

I've re-run IPTV Merge but no change.
When I try to access the m3u8 with X-Forward set, I'm getting a 403 error from NZ.

**Comment by matthuisman** [comment]
thanks for letting me know. the bug has been fixed and they should be back online :)
