### ISSUE TITLE
Youtube for trailers | Fails in UWP (Xbox)

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#705]
```
2024-03-31 19:01:16.465 T:1236    debug <general>: CPythonInvoker(20, Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\default.py): entering source directory Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube
2024-03-31 19:01:16.465 T:1236    debug <general>: CPythonInvoker(20, Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\default.py): instantiating addon using automatically obtained id of "plugin.video.youtube" dependent on version 3.0.1 of the xbmc.python api
2024-03-31 19:01:16.492 T:5116    debug <general>: POParser: PO file has Win Style Line Endings. Converted in memory to Linux LF for file: resource://resource.language.en_gb/strings.po
2024-03-31 19:01:16.494 T:5116    debug <general>: POParser: loaded 131 weather tokens
2024-03-31 19:01:16.696 T:1236    debug <general>: plugin.video.youtube - sys.path: ['Q:\\Users\\UserMgr0\\AppData\\Local\\Packages\\XBMCFoundation.Kodi_4n2hpmxwrvr6p\\LocalState\\addons\\plugin.video.youtube', 'Q:\\Users\\UserMgr0\\AppData\\Local\\Packages\\XBMCFoundation.Kodi_4n2hpmxwrvr6p\\LocalState\\addons\\script.module.slyguy\\resources\\modules', 'Q:\\Users\\UserMgr0\\AppData\\Local\\Packages\\XBMCFoundation.Kodi_4n2hpmxwrvr6p\\LocalState\\addons\\slyguy.dependencies\\resources\\modules', 'S:\\Program Files\\WindowsApps\\XBMCFoundation.Kodi_20.90.910.70_x64__4n2hpmxwrvr6p\\system\\python\\DLLs', 'S:\\Program Files\\WindowsApps\\XBMCFoundation.Kodi_20.90.910.70_x64__4n2hpmxwrvr6p\\system\\python\\Lib', 'S:\\Program Files\\WindowsApps\\XBMCFoundation.Kodi_20.90.910.70_x64__4n2hpmxwrvr6p\\system\\python\\Lib\\site-packages']
2024-03-31 19:01:17.253 T:1236    debug <general>: plugin.video.youtube - OpenSSL 1.1.1q  5 Jul 2022
2024-03-31 19:01:17.404 T:1236    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'FileNotFoundError'>
                                                   Error Contents: Could not find module 'kernel32' (or one of its dependencies). Try using the full path with constructor syntax.
                                                   Traceback (most recent call last):
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.90.910.70_x64__4n2hpmxwrvr6p\system\python\Lib\site-packages\Cryptodome\Util\_raw_api.py", line 84, in <module>
                                                       from cffi import FFI
                                                   ModuleNotFoundError: No module named 'cffi'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\default.py", line 1, in <module>
                                                       from resources.lib.plugin import plugin
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\plugin.py", line 12, in <module>
                                                       from .yt_dlp import YoutubeDL
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\yt_dlp\__init__.py", line 19, in <module>
                                                       from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\yt_dlp\cookies.py", line 21, in <module>
                                                       from .aes import (
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\yt_dlp\aes.py", line 5, in <module>
                                                       from .dependencies import Cryptodome
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\yt_dlp\dependencies\__init__.py", line 71, in <module>
                                                       from . import Cryptodome
                                                     File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\resources\lib\yt_dlp\dependencies\Cryptodome.py", line 19, in <module>
                                                       from Cryptodome.Cipher import AES, PKCS1_OAEP, Blowfish, PKCS1_v1_5
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.90.910.70_x64__4n2hpmxwrvr6p\system\python\Lib\site-packages\Cryptodome\Cipher\__init__.py", line 27, in <module>
                                                       from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.90.910.70_x64__4n2hpmxwrvr6p\system\python\Lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 29, in <module>
                                                       from Cryptodome.Util._raw_api import (load_pycryptodome_raw_lib,
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.90.910.70_x64__4n2hpmxwrvr6p\system\python\Lib\site-packages\Cryptodome\Util\_raw_api.py", line 165, in <module>
                                                       import ctypes
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.90.910.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 468, in <module>
                                                       GetLastError = windll.kernel32.GetLastError
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.90.910.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 443, in __getattr__
                                                       dll = self._dlltype(name)
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.90.910.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 373, in __init__
                                                       self._handle = _dlopen(self._name, mode)
                                                   FileNotFoundError: Could not find module 'kernel32' (or one of its dependencies). Try using the full path with constructor syntax.
                                                   -->End of Python script error report<--
                                                   
2024-03-31 19:01:17.405 T:1236    debug <general>: CPythonInvoker::onExecutionDone(20, Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.youtube\default.py)
```

**Comment by matthuisman** [comment]
kodi issue here:
https://github.com/xbmc/xbmc/issues/24746

Might be able to work around it by modifying the addon to not need it or use a pure python implementation?

**Comment by matthuisman** [comment]
fixed with [plugin.video.youtube -> v99.0.6](https://github.com/matthuisman/slyguy.addons/commit/adb332e017104dc8f655400ea91b2bd81093bdf9)
