### ISSUE TITLE
HBO MAX (0.6.0)  - error defaultaudioselection with champions league Today Matches on live

### ISSUE THREAD

**Issue by daplam84** [matthuisman/slyguy.addons#71]
When a soccer math is selected to play, hbomax throws error of defaultaudioselection. Account HBO is from Mexico. 
It only happens with the on live soccer matches. Movies and series work correctly.

    Dist- LibreEelec (Official) 9.2.8
    SlyGuy Common Version - 0.43.9
    HBO Max Version - 0.6.0
    Arch: RPi4

**Steps to reproduce**

Launch the HBO Max add-on and try to play on live soccer match.  

**Actual behaviour**

Below error shows up:
![image](https://user-images.githubusercontent.com/91572865/135173727-585dd5ee-64b6-4b33-9736-a6c080cbb230.png)

Log:
![image](https://user-images.githubusercontent.com/91572865/135174155-de9d506b-29cc-413e-a6fb-5903c0017484.png)

**Comment by matthuisman** [comment]
thanks for the good bug report

please try  0.6.1 that i just pushed
you can force update by following the below:
https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html

I cant test as my HBO doesnt have sport, but let me know if it doesnt work

**Comment by daplam84** [comment]
It worked, it is needed to have Accessibility Audio option = Enabled, if not enabled, video is not displayed, just listen the audio.

**Comment by matthuisman** [comment]
oh really? thats strange.

**Comment by matthuisman** [comment]
can you try force update and then test that again? (just pushed some changes)

**Comment by daplam84** [comment]
0.6.2 - It didn't work. Now any video is played (movies, series, on live). It does not displayed error, but video is not started.

**Slyguy errors:**

![image](https://user-images.githubusercontent.com/91572865/135319947-7392303c-4154-43d7-9d01-037ec14a80fc.png)

**Kodi log:**

ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2021-09-29 12:25:10.132 T:2520224576   ERROR: slyguy.hbo.max - global name 'enable_accessibility' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 98, in decorated_function
                                                data = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/slyguy.hbo.max/resources/lib/plugin.py", line 450, in mpd_request
                                                if not enable_accessibility and adap_set.getElementsByTagName('Accessibility'):
                                            NameError: global name 'enable_accessibility' is not defined
2021-09-29 12:25:10.136 T:2453472064   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
2021-09-29 12:25:10.136 T:2453472064   ERROR: CCurlFile::Open failed with code 0 for http://127.0.0.1:52103/https://live.lln.latam.hbomaxcdn.com/cmaf/live/2031610/dash/cenc/23821/master.mpd:
2021-09-29 12:25:10.136 T:2453472064   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://127.0.0.1:52103/https://live.lln.latam.hbomaxcdn.com/cmaf/live/2031610/dash/cenc/23821/master.mpd
2021-09-29 12:25:10.136 T:2453472064   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://127.0.0.1:52103/https://live.lln.latam.hbomaxcdn.com/cmaf/live/2031610/dash/cenc/23821/master.mpd)
2021-09-29 12:25:10.137 T:2453472064   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://slyguy.hbo.max/?_=play&_play=1&profile_id=39f5a02b-faf7-40d1-acf7-b5c94a1b488b&slug=urn%3Ahbo%3Afeature%3AGYS1LKg88QMIvwgEAAAAQ]

**Comment by matthuisman** [comment]
oops, that should now be fixed with 0.6.3

**Comment by daplam84** [comment]
Cool, everything working fine with 0.6.3
