### ISSUE TITLE
[ESPN+] Fails to display list of live streams (ASCII vs. Unicode issue)

### ISSUE THREAD

**Issue by dennis-gr** [matthuisman/slyguy.addons#72]
Navigating to 'Live' caused the following error today:

```
ERROR: slyguy.espn - 'ascii' codec can't encode character u'\xf3' in position 22: ordinal not in range(128)
Traceback (most recent call last):
  File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 31, in throwable
    yield
  File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 120, in dispatch
    function(**params)
  File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 64, in decorated_function
    item = f(*args, **kwargs)
  File "/storage/.kodi/addons/slyguy.espn/resources/lib/plugin.py", line 77, in live
    subtitle = '{} - {}'.format(catalog.get('sport' ,''), catalog.get('league', '')).strip().strip('-').strip()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 22: ordinal not in range(128)
```

It's working again ATM as the offending stream is gone now.

**Comment by matthuisman** [comment]
thanks for the report
should be fixed with 0.1.6
