### ISSUE TITLE
No module named 'six.moves'

### ISSUE THREAD

**Issue by david-hazi** [matthuisman/slyguy.addons#726]
Kodi 21, Ubuntu 24.04

This is a fresh Kodi 21 compiled from source. First I've installed the slyguy addon -> ok, than installed Disney+ -> error came up.

```
2024-04-27 21:23:10.227 T:25929   error <general>: Traceback (most recent call last):
2024-04-27 21:23:10.227 T:25929   error <general>:
2024-04-27 21:23:10.227 T:25929   error <general>:   File "/var/lib/kodi/.kodi/addons/script.module.slyguy/service.py", line 8, in <module>
2024-04-27 21:23:10.227 T:25929   error <general>:
2024-04-27 21:23:10.227 T:25929   error <general>:   File "/var/lib/kodi/.kodi/addons/script.module.slyguy/resources/lib/service.py", line 6, in <module>
2024-04-27 21:23:10.227 T:25929   error <general>:
2024-04-27 21:23:10.227 T:25929   error <general>:   File "/var/lib/kodi/.kodi/addons/script.module.slyguy/resources/modules/slyguy/settings.py", line 9, in <module>
2024-04-27 21:23:10.227 T:25929   error <general>:
2024-04-27 21:23:10.227 T:25929   error <general>:   File "/var/lib/kodi/.kodi/addons/script.module.slyguy/resources/modules/slyguy/util.py", line 19, in <module>
2024-04-27 21:23:10.227 T:25929   error <general>:
2024-04-27 21:23:10.227 T:25929   error <general>: ModuleNotFoundError: No module named 'six.moves'
```

**Comment by matthuisman** [comment]
You must install the add-ons via the slyguy repo (not zip). Your missing a
bunch of dependencies . Try again

**Comment by david-hazi** [comment]
I've installed the slyguy addon from:
repository.slyguy.zip

Than I've installed Disney+ from the Kodi UI.

**Comment by david-hazi** [comment]
Dependencies are also here, it worked with the previous kodi version.

**Comment by david-hazi** [comment]
#reopen

**Comment by matthuisman** [comment]
full kodi debug log plz

**Comment by david-hazi** [comment]
[kodi.txt](https://github.com/matthuisman/slyguy.addons/files/15139944/kodi.txt)

**Comment by matthuisman** [comment]
/var/lib/kodi/.kodi/addons/slyguy.dependencies/resources/modules should contain a six.py module.

Id suggest you try re-installing it

**Comment by david-hazi** [comment]
root@chuwi:/var/lib/kodi/.kodi# ls -l /var/lib/kodi/.kodi/addons/slyguy.dependencies/resources/modules/six.py
-rw-r--r-- 1 kodi kodi 34159 Mar 18 08:16 /var/lib/kodi/.kodi/addons/slyguy.dependencies/resources/modules/six.py

**Comment by david-hazi** [comment]
```
root@chuwi:/var/lib/kodi/.kodi/addons/slyguy.dependencies/resources/modules# wget https://raw.githubusercontent.com/matthuisman/slyguy.addons/master/slyguy.dependencies/resources/modules/six.py
--2024-04-27 23:10:27--  https://raw.githubusercontent.com/matthuisman/slyguy.addons/master/slyguy.dependencies/resources/modules/six.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34159 (33K) [text/plain]
Saving to: ‘six.py.1’

six.py.1                             100%[=====================================================================>]  33.36K  --.-KB/s    in 0.02s

2024-04-27 23:10:27 (2.14 MB/s) - ‘six.py.1’ saved [34159/34159]

root@chuwi:/var/lib/kodi/.kodi/addons/slyguy.dependencies/resources/modules# diff six.py*
root@chuwi:/var/lib/kodi/.kodi/addons/slyguy.dependencies/resources/modules# diff six.py six.py.1
root@chuwi:/var/lib/kodi/.kodi/addons/slyguy.dependencies/resources/modules#

```

**Comment by david-hazi** [comment]
six.py has never version: 1.16

**Comment by matthuisman** [comment]
ok. its a python 3.12 import thing. i can replicate with 3.12 on windows. ill work on a fix

**Comment by david-hazi** [comment]
just update the six.py, it is working for me.

**Comment by matthuisman** [comment]
yup. but also need to add a new looseversion

**Comment by matthuisman** [comment]
should now be fixed with
[slyguy.dependencies -> v0.0.18](https://github.com/matthuisman/slyguy.addons/commit/5010c99587de49e386b5f8a835793ad0bd2a65bf)
&
[script.module.slyguy -> v0.78.6](https://github.com/matthuisman/slyguy.addons/commit/9c46e431ed6e96864c67477a63162792b50fd90e)

**Comment by david-hazi** [comment]
thank you!
