### ISSUE TITLE
[Paramount+] Fails to play live stream (ASCII vs. Unicode issue)

### ISSUE THREAD

**Issue by dennis-gr** [matthuisman/slyguy.addons#73]
Trying to play a football match from one of the South American leagues fails with:

```
ERROR: slyguy.paramount.plus - 'ascii' codec can't encode character u'\xe3' in position 1115: ordinal not in range(128)
       Traceback (most recent call last):
         File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 31, in throwable
           yield
         File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 120, in dispatch
           function(**params)
         File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 64, in decorated_function
           item = f(*args, **kwargs)
         File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 55, in decorated_function
           return f(*args, **kwargs)
         File "/storage/.kodi/addons/slyguy.paramount.plus/resources/lib/plugin.py", line 660, in play_channel
           play_path, license_url, token, data = api.play(selected['videoContentId'])
         File "/storage/.kodi/addons/slyguy.paramount.plus/resources/lib/api.py", line 302, in play
           root = ET.fromstring(resp.text)
         File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
         File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1657, in feed
       UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 1115: ordinal not in range(128)
```

**Comment by matthuisman** [comment]
should now be fixed with 0.2.9
