### ISSUE TITLE
Slyguycommon error

### ISSUE THREAD

**Issue by jakethekiwi** [matthuisman/slyguy.addons#736]
Hi Matt as of last night having errors with all plugins and also slyguy common nothing works anymore tryed to uninstall everything and start again same error
Traceback (most recent call last):
                                              File "/storage/.kodi/addons/slyguy.9now/default.py", line 3, in <module>
                                                from resources.lib.plugin import plugin
                                              File "/storage/.kodi/addons/slyguy.9now/resources/lib/plugin.py", line 7, in <module>
                                                from slyguy import plugin, gui, settings, userdata, inputstream
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 12, in <module>
                                                from . import router, gui, settings, userdata, inputstream, signals, migrate, bookmarks, mem_cache
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/gui.py", line 16, in <module>
                                                from .session import Session
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 41, in <module>
                                                SSL_OPTIONS = ssl.OP_NO_SSLv2 | ssl.OP_NO_SSLv3 | ssl.OP_NO_COMPRESSION | ssl.OP_NO_TICKET
                                            AttributeError: 'module' object has no attribute 'OP_NO_TICKET'
                                            -->End of Python script error report<--
2024-05-08 21:08:19.113 T:3464889216   ERROR: GetDirectory - Error getting plugin://slyguy.9now/
2024-05-08 21:08:19.134 T:4063252544   ERROR: CGUIMediaWindow::GetDirectory(plugin://slyguy.9now/) failed: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'OP_NO_TICKET'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.slyguy/default.py", line 7, in <module>
                                                from resources.lib.plugin import plugin
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/lib/plugin.py", line 5, in <module>
                                                from slyguy import plugin, gui
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 12, in <module>
                                                from . import router, gui, settings, userdata, inputstream, signals, migrate, bookmarks, mem_cache
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/gui.py", line 16, in <module>
                                                from .session import Session
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 41, in <module>
                                                SSL_OPTIONS = ssl.OP_NO_SSLv2 | ssl.OP_NO_SSLv3 | ssl.OP_NO_COMPRESSION | ssl.OP_NO_TICKET
                                            AttributeError: 'module' object has no attribute 'OP_NO_TICKET'
                                            -->End of Python script error report<--
Hope you can help
By the way mate love your work absolute champ

**Comment by matthuisman** [comment]
What version Kodi and what system?

**Comment by jakethekiwi** [comment]
Coreelec 9.2.8
18.9 leia

**Comment by vitminc** [comment]
Replacement:
SSL_OPTIONS = ssl.OP_NO_SSLv2 | ssl.OP_NO_SSLv3 | ssl.OP_NO_COMPRESSION | ssl.OP_NO_TICKET
to 
SSL_OPTIONS = ssl.OP_NO_SSLv2 | ssl.OP_NO_SSLv3 | ssl.OP_NO_COMPRESSION
solves problem



2024-05-08 13:02:50.773 T:139762211084416  NOTICE: Starting Kodi (18.5 Git:18.5-Leia). Platform: Linux x86 64-bit
2024-05-08 13:02:50.773 T:139762211084416  NOTICE: Using Release Kodi x64 build
2024-05-08 13:02:50.773 T:139762211084416  NOTICE: Kodi compiled 2020-01-09 by GCC 8.3.0 for Linux x86 64-bit version 5.1.16 (327952)
2024-05-08 13:02:50.773 T:139762211084416  NOTICE: Running on LibreELEC (community): devel-20200109033139-7a16627 9.2, kernel: Linux x86 64-bit version 5.1.16
2024-05-08 13:02:50.774 T:139762211084416  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2024-05-08 13:02:50.774 T:139762211084416  NOTICE: Host CPU: Intel(R) Atom(TM) CPU D525 @ 1.80GHz, 4 cores available




2024-05-08 13:04:49.384 T:139759560599296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'OP_NO_TICKET'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.slyguy/default.py", line 7, in <module>
                                                from resources.lib.plugin import plugin
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/lib/plugin.py", line 5, in <module>
                                                from slyguy import plugin, gui
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 12, in <module>
                                                from . import router, gui, settings, userdata, inputstream, signals, migrate, bookmarks, mem_cache
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/gui.py", line 16, in <module>
                                                from .session import Session
                                              File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 41, in <module>
                                                SSL_OPTIONS = ssl.OP_NO_SSLv2 | ssl.OP_NO_SSLv3 | ssl.OP_NO_COMPRESSION | ssl.OP_NO_TICKET
                                            AttributeError: 'module' object has no attribute 'OP_NO_TICKET'
                                            -->End of Python script error report<--

**Comment by jakethekiwi** [comment]
Awesome thanks mate

**Comment by vitminc** [comment]
Thanks. It works.
