### ISSUE TITLE
Samsung TV: SlyProxy & USBB800001O7

### ISSUE THREAD

**Issue by terasecond** [matthuisman/slyguy.addons#760]
When the SlyProxy is enabled the following error occurs when attempting to play USBB800001O7 (PBS Digital Studios).
The channel however plays just fine if the proxy is disabled.

```
2024-06-09 18:29:45.193 T:1119     info <general>: VideoPlayer::OpenFile: plugin://slyguy.samsung.tv.plus/?_=play&_play=1&id=USBB800001O7&_is_live=1&_noresume=.pvr
2024-06-09 18:29:45.194 T:1430     info <general>: Creating InputStream
2024-06-09 18:29:45.199 T:1430     info <general>: Creating Demuxer
2024-06-09 18:29:45.710 T:1433    error <general>: script.module.slyguy - Invalid m3u8
                                                   Traceback (most recent call last):
                                                     File "/home/account/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 298, in do_GET
                                                       self._parse_m3u8(response)
                                                     File "/home/account/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 1235, in _parse_m3u8
                                                       raise Exception('Invalid m3u8')
                                                   Exception: Invalid m3u8
2024-06-09 18:29:45.711 T:1430    error <general>: OpenDemuxStream - Error creating demuxer
```

OS: Raspberry Pi OS 64bit
Hardware: RPi4B
Kodi: 20.5 Nexus
Addon: slyguy.samsung.tv.plus

**Comment by matthuisman** [comment]
fixed with [script.module.slyguy -> v0.81.0](https://github.com/matthuisman/slyguy.addons/commit/230c32228dc07ce2df3225001d6de4fd23f3765b)

that channel had a bad relative url that cause havoc with curl + the proxy address.
Fixed by converting relative paths to abs paths
