### ISSUE TITLE
Some TVNZ+ streams fail to play

### ISSUE THREAD

**Issue by waynethomas69** [matthuisman/slyguy.addons#790]
Most TVNZ+ streams work, however all of the full-length football games from EURO2024 fail. The highlights for each game do work, as do the full-length streams of other sports that I have tried (for instance, WRC).
I had thought it might be something to do with the length of stream since everything I normally watch are no longer than 1hr 30min, however just checked a 2hr movie which played fine.

Below is kodi.log when attempting to play a failed stream (full-length game):
2024-07-06 10:31:18.051 T:9627     info <general>: plugin.video.tvnz.ondemand - Widevine - System: Linux | Arch: armv7
2024-07-06 10:31:18.103 T:9627     info <general>: plugin.video.tvnz.ondemand - Widevine Current MD5: 9aff9fa1f4d1b97532a6f5c8ef2cc914
2024-07-06 10:31:18.134 T:965      info <general>: VideoPlayer::OpenFile: plugin://plugin.video.tvnz.ondemand/?_=play&_play=1&mediakindhref=https%3A%2F%2Fapis-public-prod.tvnz.io%2Fplayback%2Fv1%2F57cd7be8-78a8-4a88-a2d6-d67b29d516fb
2024-07-06 10:31:18.136 T:9833     info <general>: Creating InputStream
2024-07-06 10:31:18.138 T:9833  warning <general>: AddOnLog: inputstream.adaptive: Set headers to the manifest url by using pipe "|" char is deprecated, and will be removed in future.
                                                   Use "inputstream.adaptive.manifest_headers" and "inputstream.adaptive.stream_headers" properties instead.
2024-07-06 10:31:18.142 T:9833     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2024-07-06 10:31:18.142 T:9833    error <general>: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2024-07-06 10:31:19.268 T:9838    error <general>: script.module.slyguy - '>' not supported between instances of 'str' and 'float'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 298, in do_GET
                                                       self._parse_dash(response)
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 715, in _parse_dash
                                                       selected = self._quality_select(streams)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 397, in _quality_select
                                                       streams = sorted(qualities, key=quality_compare, reverse=True)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 361, in compare
                                                       if a['frame_rate'] > b['frame_rate']:
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: '>' not supported between instances of 'str' and 'float'
2024-07-06 10:31:19.270 T:9833     info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 1, Type: VOD)
2024-07-06 10:31:19.271 T:9833     info <general>: Creating Demuxer
2024-07-06 10:31:19.271 T:9833     info <general>: Opening stream: 1001 source: 256
2024-07-06 10:31:19.777 T:9833    error <general>: AddOnLog: inputstream.adaptive: No MOOV in stream!
2024-07-06 10:31:19.777 T:9833  warning <general>: OpenStream - Unsupported stream 1001. Stream disabled.
2024-07-06 10:31:19.778 T:9833     info <general>: Process - eof reading from demuxer
2024-07-06 10:31:19.778 T:9833     info <general>: CVideoPlayer::OnExit()
2024-07-06 10:31:19.778 T:9833     info <general>: VideoPlayer: eof, waiting for queues to empty
2024-07-06 10:31:19.779 T:9833     info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2024-07-06 10:31:19.801 T:965      info <general>: CVideoPlayer::CloseFile()
2024-07-06 10:31:19.801 T:965      info <general>: VideoPlayer: waiting for threads to exit
2024-07-06 10:31:19.801 T:965      info <general>: VideoPlayer: finished waiting
2024-07-06 10:31:19.801 T:965      info <general>: CVideoPlayer::CloseFile()
2024-07-06 10:31:19.801 T:965      info <general>: VideoPlayer: waiting for threads to exit
2024-07-06 10:31:19.801 T:965      info <general>: VideoPlayer: finished waiting

Here is the log for a stream that plays successfully (game highlights):
2024-07-06 10:44:05.394 T:9627     info <general>: plugin.video.tvnz.ondemand - Widevine - System: Linux | Arch: armv7
2024-07-06 10:44:05.443 T:9627     info <general>: plugin.video.tvnz.ondemand - Widevine Current MD5: 9aff9fa1f4d1b97532a6f5c8ef2cc914
2024-07-06 10:44:05.480 T:965      info <general>: VideoPlayer::OpenFile: plugin://plugin.video.tvnz.ondemand/?_=play&_play=1&brightcoveId=6356757994112
2024-07-06 10:44:05.484 T:24006    info <general>: Creating InputStream
2024-07-06 10:44:05.487 T:24006 warning <general>: AddOnLog: inputstream.adaptive: Set headers to the manifest url by using pipe "|" char is deprecated, and will be removed in future.
                                                   Use "inputstream.adaptive.manifest_headers" and "inputstream.adaptive.stream_headers" properties instead.
2024-07-06 10:44:05.492 T:24006    info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2024-07-06 10:44:05.492 T:24006   error <general>: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2024-07-06 10:44:06.552 T:24006    info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 2, Type: VOD)
2024-07-06 10:44:07.880 T:24015    info <general>: script.module.slyguy - WV License response OK and returned data
2024-07-06 10:44:09.023 T:24006    info <general>: Creating Demuxer
2024-07-06 10:44:09.023 T:24006    info <general>: Opening stream: 1001 source: 256
2024-07-06 10:44:13.406 T:24006    info <general>: Creating video codec with codec id: 27
2024-07-06 10:44:13.407 T:24006    info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder V4L2 mem2mem H.264 decoder wrapper
2024-07-06 10:44:13.419 T:24006    info <general>: Creating video thread
2024-07-06 10:44:13.419 T:24040    info <general>: running thread: video_thread
2024-07-06 10:44:13.419 T:24006    info <general>: Opening stream: 1002 source: 256
2024-07-06 10:44:13.460 T:24006    info <general>: Finding audio codec for: 86018
2024-07-06 10:44:13.461 T:24006    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2024-07-06 10:44:13.461 T:24006    info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2024-07-06 10:44:13.461 T:24006    info <general>: Creating audio thread
2024-07-06 10:44:13.461 T:24043    info <general>: running thread: CVideoPlayerAudio::Process()
2024-07-06 10:44:13.785 T:24043    info <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
2024-07-06 10:44:13.806 T:980      info <general>: CActiveAESink::OpenSink - initialize sink
2024-07-06 10:44:14.006 T:980      info <general>: CAESinkALSA::Initialize - Attempting to open device "@"
2024-07-06 10:44:14.009 T:980      info <general>: CAESinkALSA::Initialize - Opened device "sysdefault"
2024-07-06 10:44:14.009 T:980      info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2024-07-06 10:44:14.010 T:980      info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3

**Comment by matthuisman** [comment]
thanks for the good bug report :) 
It allowed me to quickly re-create the issue and fix it
fixed with [script.module.slyguy -> v0.83.3](https://github.com/matthuisman/slyguy.addons/commit/fb41386df7f2cd05f09a40fb564ffde37b336d47)
