### ISSUE TITLE
Optus Sport guide data empty

### ISSUE THREAD

**Issue by timble70** [matthuisman/slyguy.addons#796]
Also updating common files fails. Thanks.

![20240714_071833](https://github.com/user-attachments/assets/b649581b-cc8d-498d-8306-ab07378b6938)

**Comment by matthuisman** [comment]
id recommend reinstalling the repo. not seeing any other issues with updating

**Comment by matthuisman** [comment]
also, https://sport.optus.com.au/videos/v42463/optus-sport-1 doesnt even have guide data so its a problem their end

**Comment by timble70** [comment]
Tried reinstalling, but it's not downloading IPTV Merge.
![Uploading 20240714_105909.jpg…]()

**Comment by matthuisman** [comment]
You'll need to look at your Kodi log and see what's going on

**Comment by timble70** [comment]
Cheers Matt. Does this means anything to you? Thanks.

2024-07-14 12:05:50.417 T:11264   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'slyguy.database' has no attribute 'init'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iptv.merge/default.py", line 1, in <module>
                                                       from resources.lib.plugin import plugin
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iptv.merge/resources/lib/plugin.py", line 15, in <module>
                                                       from .models import Playlist, EPG, Channel, Override, merge_info
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iptv.merge/resources/lib/models.py", line 743, in <module>
                                                       database.init([Playlist, EPG, Channel, Override])
                                                       ^^^^^^^^^^^^^
                                                   AttributeError: module 'slyguy.database' has no attribute 'init'
                                                   -->End of Python script error report<--
[kodi.log](https://github.com/user-attachments/files/16215409/kodi.log)

**Comment by matthuisman** [comment]
Your slyguy common is too old. That needs to be the latest

**Comment by timble70** [comment]
Thanks Matt. The merge is working again. Optus 1 is still empty but the other Optus channels have data, so I guess it's just empty. The EPG source would be the same for all 3 channels wouldn't it?
![Uploading 20240714_144009.jpg…]()

**Comment by matthuisman** [comment]
Ive linked to their website. Ask Optus about it
