### ISSUE TITLE
Can't login to HBO Max

### ISSUE THREAD

**Issue by nre-ableton** [matthuisman/slyguy.addons#814]
I've just installed the SlyGuy addons with a new HBO Max account, and I can't login.

## Email/Password Login

When logging in with an email address and password, I get an authentication error from the add-on, despite me being 100% certain that the login information is correct (I also changed my password to something more trivial to make sure there weren't any typos in the password entry). Enabling debug logging and checking out `kodi.log` shows this exception:

```
2024-07-27 10:15:19.236 T:967     debug <general>: slyguy.hbo.max - Attempt 1/1: POST https://sessions.api.hbo.com/sessions/v1/clientConfig
2024-07-27 10:15:19.261 T:967     debug <general>: slyguy.hbo.max - DNS Resolve: sessions.api.hbo.com -> system dns -> 151.101.9.119, 151.101.9.119, 151.101
.9.119
2024-07-27 10:15:19.406 T:967     debug <general>: slyguy.hbo.max - Opening secure connection on port 443 to 151.101.9.119 ('TLS_AES_128_GCM_SHA256', 'TLSv1
.3', 128)
2024-07-27 10:15:19.498 T:967     debug <general>: slyguy.hbo.max - Cache Set: config
2024-07-27 10:15:19.499 T:967     debug <general>: slyguy.hbo.max - Attempt 1/1: POST https://oauth-emea.api.hbo.com/auth/tokens
2024-07-27 10:15:19.527 T:967     debug <general>: slyguy.hbo.max - DNS Resolve: oauth-emea.api.hbo.com -> system dns -> 151.101.9.119, 151.101.9.119, 151.1
01.9.119
2024-07-27 10:15:19.665 T:967     debug <general>: slyguy.hbo.max - Opening secure connection on port 443 to 151.101.9.119 ('TLS_AES_128_GCM_SHA256', 'TLSv1
.3', 128)
2024-07-27 10:15:19.756 T:967     debug <general>: slyguy.hbo.max - SIGNAL: on_error
2024-07-27 10:15:19.757 T:967     debug <general>: slyguy.hbo.max - Mem Cache: Deleted 1 Rows
2024-07-27 10:15:19.757 T:967     debug <general>: slyguy.hbo.max - SIGNAL: on_close
2024-07-27 10:15:19.768 T:967     debug <general>: slyguy.hbo.max - API request failed
                                                   Server Error: The email address or password is incorrect. Please try again.
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 53, in thro
wable
                                                       yield
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 127, in disp
atch
                                                       function(**params)
                                                     File "/storage/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 60, in decor
ated_function
                                                       item = f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.hbo.max/resources/lib/plugin.py", line 411, in login
                                                       if index == -1 or not options[index][1]():
                                                                             ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/slyguy.hbo.max/resources/lib/plugin.py", line 442, in _email_password
                                                       api.login(email, password)
                                                     File "/storage/.kodi/addons/slyguy.hbo.max/resources/lib/api.py", line 177, in login
                                                       self._oauth_token(payload)
                                                     File "/storage/.kodi/addons/slyguy.hbo.max/resources/lib/api.py", line 76, in _oauth_token
                                                       self._check_errors(data)
                                                     File "/storage/.kodi/addons/slyguy.hbo.max/resources/lib/api.py", line 204, in _check_errors
                                                       raise APIError(_(error, msg=error_msg))
                                                   resources.lib.api.APIError: API request failed
                                                   Server Error: The email address or password is incorrect. Please try again.
```

Although error thrown is `APIError`, the above stacktrace leads me to believe that something else is wrong.

## Device Code

There's a few problems when authenticating with a device code. The URL given (https://hbomax.com/tvlogin) simply redirects to https://play.max.com. Poking around a bit on HBO's website leads me to believe that the new URL is https://auth.max.com/link. However, the auth codes also seem to have changed; this add-on generates a 6-digit alphanumeric code (ie, `HY432X`), but HBO's website only accepts 6-digit numeric codes. So I'm guessing something needs to be updated here.

**Comment by matthuisman** [comment]
Maybe you meant to be using the MAX add-on? They are different. HBO max is
the old name

**Comment by nre-ableton** [comment]
Yes, sorry, I didn't realize that. Sorry for the noise!

(Also, should the other add-on be renamed to include "deprecated" somewhere? Just a thought).

**Comment by matthuisman** [comment]
Some countries still use the old service I believe
