### ISSUE TITLE
API request failed

### ISSUE THREAD

**Issue by shibaevivan** [matthuisman/slyguy.addons#865]
2024-08-21 11:53:16.412 T:1517285568   DEBUG: slyguy.disney.plus - API request failed
                                            Server Error: upstream: 'token'
                                            Received error response from upstream error with status '400' and description 'forbidden-location'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.module.slyguy/resources/modules/slyguy/signals.py", line 53, in throwable
                                                yield
                                              File "/home/pi/.kodi/addons/script.module.slyguy/resources/modules/slyguy/router.py", line 136, in dispatch
                                                function(**params)
                                              File "/home/pi/.kodi/addons/script.module.slyguy/resources/modules/slyguy/plugin.py", line 59, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/slyguy.disney.plus/resources/lib/plugin.py", line 67, in login
                                                if index == -1 or not options[index][1]():
                                              File "/home/pi/.kodi/addons/slyguy.disney.plus/resources/lib/plugin.py", line 95, in _email_password
                                                token = api.register_device()
                                              File "/home/pi/.kodi/addons/slyguy.disney.plus/resources/lib/api.py", line 98, in register_device
                                                self._check_errors(data)
                                              File "/home/pi/.kodi/addons/slyguy.disney.plus/resources/lib/api.py", line 223, in _check_errors
                                                raise APIError(error_msg)
                                            APIError: API request failed
                                            Server Error: upstream: 'token'
                                            Received error response from upstream error with status '400' and description 'forbidden-location'

I've tried with any proxy. doesn't work for me

**Comment by matthuisman** [comment]
That's their api blocking your access. Nothing I can do about that sorry. If official apps, website don't work then this won't either
