### ISSUE TITLE
Smart URL Actions giving "IndexError: pop from empty list" in Kodi 21.1

### ISSUE THREAD

**Issue by MJC-code** [matthuisman/slyguy.addons#880]
Full kodi log [https://pastebin.com/XuSYpduW](url)

I'm trying to use Smart URL Actions on Kodi 21.1 on Windows 11, logged in as a SlyGuy supporter, to use some Oz TV addons from NZ, which I have had working on earlier Kodi versions.

I've put a urls.txt file containing r:[dns4me ip] *
into userdata\addon_data\script.module.slyguy but it errors out with the final lines of the log listed below:

I'm not sure whether it's related, but I notice that in Kodi 21, addons no longer seem to create a folder in userdata\addon_data\  after the first run, but only seem to create a folder in Kodi\addons

`2024-08-30 23:07:36.111 T:20016   error <general>: 
                                                   
2024-08-30 23:07:36.111 T:20016   error <general>: Exception happened during processing of request from
2024-08-30 23:07:36.111 T:20016   error <general>:  
2024-08-30 23:07:36.111 T:20016   error <general>: ('127.0.0.1', 50971)
2024-08-30 23:07:36.111 T:20016   error <general>: 
                                                   
2024-08-30 23:07:36.111 T:20016   error <general>: Traceback (most recent call last):
                                                   
2024-08-30 23:07:36.111 T:20016   error <general>: 
2024-08-30 23:07:36.111 T:20016   error <general>:   File "C:\Program Files\Kodi\system\python\Lib\socketserver.py", line 683, in process_request_thread
                                                       self.finish_request(request, client_address)
                                                   
2024-08-30 23:07:36.111 T:20016   error <general>: 
2024-08-30 23:07:36.111 T:20016   error <general>:   File "C:\Program Files\Kodi\system\python\Lib\socketserver.py", line 360, in finish_request
                                                       self.RequestHandlerClass(request, client_address, self)
                                                   
2024-08-30 23:07:36.111 T:20016   error <general>: 
2024-08-30 23:07:36.111 T:20016   error <general>:   File "C:\Users\Mark\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 129, in __init__
                                                       BaseHTTPRequestHandler.__init__(self, request, client_address, server)
                                                   
2024-08-30 23:07:36.111 T:20016   error <general>: 
2024-08-30 23:07:36.111 T:20016   error <general>:   File "C:\Program Files\Kodi\system\python\Lib\socketserver.py", line 747, in __init__
                                                       self.handle()
                                                   
2024-08-30 23:07:36.111 T:20016   error <general>: 
2024-08-30 23:07:36.111 T:20016   error <general>:   File "C:\Program Files\Kodi\system\python\Lib\http\server.py", line 434, in handle
                                                       self.handle_one_request()
                                                   
2024-08-30 23:07:36.111 T:20016   error <general>: 
2024-08-30 23:07:36.111 T:20016   error <general>:   File "C:\Program Files\Kodi\system\python\Lib\http\server.py", line 422, in handle_one_request
                                                       method()
                                                   
2024-08-30 23:07:36.111 T:20016   error <general>: 
2024-08-30 23:07:36.111 T:20016   error <general>:   File "C:\Users\Mark\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 1416, in do_HEAD
                                                       response = self._proxy_request('HEAD', url)
                                                   
2024-08-30 23:07:36.112 T:20016   error <general>: 
2024-08-30 23:07:36.112 T:20016   error <general>:   File "C:\Users\Mark\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 1345, in _proxy_request
                                                       session.set_dns_rewrites(self._session.get('dns_rewrites', []))
                                                   
2024-08-30 23:07:36.112 T:20016   error <general>: 
2024-08-30 23:07:36.112 T:20016   error <general>:   File "C:\Users\Mark\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\session.py", line 253, in set_dns_rewrites
                                                       pattern = entries.pop()
                                                   
2024-08-30 23:07:36.112 T:20016   error <general>: 
2024-08-30 23:07:36.112 T:20016   error <general>: IndexError: pop from empty list
                                                   
2024-08-30 23:07:36.112 T:20016   error <general>: 
2024-08-30 23:07:36.112 T:20016   error <general>: ----------------------------------------
2024-08-30 23:07:36.112 T:20016   error <general>: 
                                                   
2024-08-30 23:07:36.112 T:20340   error <general>: script.module.slyguy - pop from empty list
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Mark\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 289, in do_GET
                                                       response = self._proxy_request('GET', url)
                                                     File "C:\Users\Mark\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 1345, in _proxy_request
                                                       session.set_dns_rewrites(self._session.get('dns_rewrites', []))
                                                     File "C:\Users\Mark\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\session.py", line 253, in set_dns_rewrites
                                                       pattern = entries.pop()
                                                   IndexError: pop from empty list
`

**Comment by matthuisman** [comment]
thanks for finding that bug.
fixed now in [script.module.slyguy -> v0.85.19](https://github.com/matthuisman/slyguy.addons/commit/fe1c99c3e4a62a8493f549b858fefeb2c13ebbc7)
