### ISSUE TITLE
Udemy will not login

### ISSUE THREAD

**Issue by peepshow-21** [matthuisman/slyguy.addons#89]
I am sure the username and password are correct.

But it fails with this in the logs.

Any idea?

2021-11-19 22:19:34.040 T:5000   DEBUG: ------ Window Deinit (DialogKeyboard.xml) ------
2021-11-19 22:19:34.182 T:8980   DEBUG: plugin.video.udemy - Attempt 1/2: POST https://www.udemy.com/api-2.0/auth/udemy-auth/login/
2021-11-19 22:19:34.527 T:8980   DEBUG: plugin.video.udemy - SIGNAL: on_error
2021-11-19 22:19:34.527 T:8980   DEBUG: plugin.video.udemy - Mem Cache: Deleted 0 Rows
2021-11-19 22:19:34.527 T:8980   DEBUG: plugin.video.udemy - SIGNAL: on_close
2021-11-19 22:19:34.528 T:8980   DEBUG: plugin.video.udemy - Failed to login.
                                            Server Message: Not found
                                            Traceback (most recent call last):
                                              File "C:\Users\michael\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\signals.py", line 31, in throwable
                                                yield
                                              File "C:\Users\michael\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\router.py", line 120, in dispatch
                                                function(**params)
                                              File "C:\Users\michael\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\plugin.py", line 64, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "C:\Users\michael\AppData\Roaming\Kodi\addons\plugin.video.udemy\resources\lib\plugin.py", line 49, in login
                                                api.login(username=username, password=password)
                                              File "C:\Users\michael\AppData\Roaming\Kodi\addons\plugin.video.udemy\resources\lib\api.py", line 121, in login
                                                raise APIError(_(_.LOGIN_ERROR, msg=data.get('detail', '')))
                                            APIError: Failed to login.
                                            Server Message: Not found
2021-11-19 22:19:34.541 T:5000   DEBUG: ------ Window Init (DialogConfirm.xml) ------
2021-11-19 22:19:35.422 T:5000   DEBUG: ------ Window Init (Pointer.xml) ------

**Comment by matthuisman** [comment]
They may have changed something. I'll take a look when I can. Weekend here which is mostly family time. May get a chance to look into tonight. They do keep trying to stop the logins, so maybe they will succeed this time so everyone forced to use their apps

**Comment by peepshow-21** [comment]
wow! :) thanks so much for the amazingly fast reply. you are putting paid businesses support services to shame here! :)

**Comment by matthuisman** [comment]
fixed now in 0.9.6

**Comment by matthuisman** [comment]
Oh yeh. Like I said, Udemy are being kind of annoying. No way around the vmp issue. Not all content uses it but more and more is
