### ISSUE TITLE
Disney+ Index out of range when no release year

### ISSUE THREAD

**Issue by andygoblins** [matthuisman/slyguy.addons#931]
I'm getting index out of range when trying to list seasons:

```debug <general>: slyguy.disney.plus - Attempt 1/1: GET https://disney.content.edge.bamgrid.com/svc/content/DmcSeriesBundle/version/6.1/region/US/audience/k-false,l-true/maturity/1450/language/en/encodedSeriesId/1xy9TAOQ0M3r
error <general>: slyguy.disney.plus - list index out of range
                                                   Traceback (most recent call last):
                                                     File "C:\Users\andygoblins\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\signals.py", line 53, in throwable
                                                       yield
                                                     File "C:\Users\andygoblins\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\router.py", line 136, in dispatch
                                                       function(**params)
                                                     File "C:\Users\andygoblins\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\plugin.py", line 74, in decorated_function
                                                       item = f(*args, **kwargs)
                                                     File "C:\Users\andygoblins\AppData\Roaming\Kodi\addons\slyguy.disney.plus\resources\lib\plugin.py", line 543, in series
                                                       item = _parse_season(row, data['series'])
                                                     File "C:\Users\andygoblins\AppData\Roaming\Kodi\addons\slyguy.disney.plus\resources\lib\plugin.py", line 375, in _parse_season
                                                       'year': row['releases'][0]['releaseYear'],
                                                   IndexError: list index out of range
```

In this example, some of the seasons return an empty 'releases' array. Could you add some sort of index check and fallback value here?

**Comment by andygoblins** [comment]
Upon further investigation, it looks like _parse_series, _parse_season, and _parse_video all call `row['releases'][0]` in various forms and crash when release array is empty.

**Comment by matthuisman** [comment]
which seasons can i reproduce on? Which country are you in?

**Comment by refbackshare** [comment]
Hello
Im getting similar issue
Poland
When i try to enter Bluey then i get this issue:
![17334775115645533715675219374779](https://github.com/user-attachments/assets/aeeb239c-b3cb-4a00-85d4-7543e5aba491)

**Comment by andygoblins** [comment]
> which seasons can i reproduce on? Which country are you in?

Whoops sorry i thought I included the CDN link in my logs.

I'm in the US and my main test case is Bluey season 1 (you know things are serious when the parent grabs debug logs for Bluey), but I've found other examples - Phineas and Ferb, Ahsoka.

**Comment by matthuisman** [comment]
thanks. should be fixed with [slyguy.disney.plus -> v0.17.7](https://github.com/matthuisman/slyguy.addons/commit/5c6ebaaf81946603b24c23c0e6204a4dbbd4fea3)

**Comment by Neriderc** [comment]
Not OP but I had this error and can confirm it's resolved in the latest version.

**Comment by Dawgofrick** [comment]
Just had this happen again. This time on Andor. Except it says line 549 instead of line 543 in series. Updated to v0.17.1 but still messed up. Other shows work fine though.

**Comment by matthuisman** [comment]
> Just had this happen again. This time on Andor. Except it says line 549 instead of line 543 in series. Updated to v0.17.1 but still messed up. Other shows work fine though.

fixed in [slyguy.disney.plus -> v0.17.8](https://github.com/matthuisman/slyguy.addons/commit/010f566ba5638e6c7729a680618c4461449a5529)
